import { requireAdminUserForPage } from "@/lib/auth/require";
import { db } from "@/lib/db/client";
import { sql } from "drizzle-orm";
import { saveArticle, publishArticle } from "./actions";
export const dynamic = "force-dynamic";
export default async function NewsAdminPage() {
  await requireAdminUserForPage("/directoryadmin/news");
  const result = await db.execute(sql`SELECT id, slug, headline, town, status, source_name, updated_at FROM news_articles ORDER BY updated_at DESC`);
  const articles = (result as any).rows ?? [];
  return <main className="mx-auto max-w-5xl px-6 py-12"><p className="text-sm font-medium uppercase tracking-wide text-brand-600">Protected editorial desk</p><h1 className="mt-1 text-3xl font-semibold">News drafts, review & publish</h1><p className="mt-2 text-slate-600">Verified facts and local reading are stored separately. Source URL is required before publishing.</p><form action={saveArticle} className="mt-8 grid gap-3 rounded-xl border p-5"><input name="headline" required placeholder="Headline" className="rounded border p-2"/><div className="grid gap-3 sm:grid-cols-2"><input name="town" required placeholder="Town" className="rounded border p-2"/><input name="sourceName" required placeholder="Source name" className="rounded border p-2"/><input name="sourceUrl" required type="url" placeholder="Source URL" className="rounded border p-2"/><input name="slug" placeholder="Slug (optional)" className="rounded border p-2"/></div><textarea name="verifiedUpdate" required placeholder="Verified update — sourced facts only" className="min-h-24 rounded border p-2"/><textarea name="localReading" required placeholder="Local reading — clearly labelled editorial interpretation" className="min-h-24 rounded border p-2"/><button className="w-fit rounded bg-brand-600 px-4 py-2 text-white">Save draft</button></form><section className="mt-10"><h2 className="text-xl font-semibold">Review queue</h2><div className="mt-3 divide-y rounded-xl border">{articles.length === 0 ? <p className="p-5 text-slate-500">No articles yet.</p> : articles.map((a: any) => <div key={a.id} className="flex items-center gap-4 p-4"><div className="flex-1"><p className="font-medium">{a.headline}</p><p className="text-sm text-slate-500">{a.town} · {a.source_name} · {a.status}</p></div>{a.status !== "published" && <form action={publishArticle}><input type="hidden" name="id" value={a.id}/><button className="rounded border px-3 py-1 text-sm">Approve & publish</button></form>}</div>)}</div></section></main>;
}
