/* Perspective-projected 3D geometry, rendered locally without external libraries.
 * VERSION HISTORY
 * v2.18.0 · 2026-09-14 · Keep automatic Arena refresh alive through transient failures and refresh immediately after tab wake.
 * v2.17.0 · 2026-09-13 · Send idle agents on varied, indirect booth-to-booth walks across the floor.
 * v2.16.0 · 2026-09-13 · Expose global Restart & sync only to the persisted Arena administrator.
 * v2.15.0 · 2026-09-13 · Compress strategy-cylinder heights so zero return is near-floor and the range remains restrained.
 * v2.14.0 · 2026-09-13 · Show truthful presence health and provide owner-scoped recovery requests.
 * v2.13.0 · 2026-09-12 · Reduce walking-cycle cadence by 25 percent.
 * v2.12.0 · 2026-09-12 · Keep the walking gait active during fine-grained perpetual milling.
 * v2.11.0 · 2026-09-12 · Animate stick agents with an articulated walking gait while moving.
 * v2.10.0 · 2026-09-12 · Move trading agents toward the exact strategy pillar they interact with.
 * v2.9.0 · 2026-09-11 · Display persistent presence separately from heartbeat health.
 * v2.8.0 · 2026-09-11 · Use total account gain since seed for stick-agent labels and colours.
 * v2.7.0 · 2026-09-11 · Compact stick-agent labels to first UUID segment and cumulative net return.
 * v2.6.0 · 2026-09-11 · Label stick agents with full ID and aggregate net return.
 * v2.5.0 · 2026-09-11 · Colour connected stick agents by aggregate open-position return direction.
 * v2.4.0 · 2026-09-11 · Scale strategy-pillar height by cumulative net return across the full floor.
 * v2.3.0 · 2026-09-11 · Render cumulative-return references after removal of manufactured unit prices.
 * v2.2.0 · 2026-09-11 · Float each new execution price above the exchange and fade it into space.
 * v2.1.0 · 2026-09-10 · Place four family booths at exchange corners and orbit one signed-return pillar per strategy.
 * v2.0.2 · 2026-09-02 · Centre a single available booth instead of reserving an empty second column.
 * v2.0.1 · 2026-09-02 · Spread small booth pages across the floor to keep narrow-screen labels readable.
 * v2.0.0 · 2026-09-02 · Reuse original perspective geometry with API-only data; no simulation data, fake returns or synthetic history.
 * v1.1.0 · 2026-08-28 · Adds return-based green/red agent haze; existing renderer predates this history.
 */
(function(){'use strict';
const MINT='#b5f5d2',AMBER='#f3b478',BLUE='#8dc8e9';
class ArenaFloor{
 constructor(canvas,data,onSelect){this.canvas=canvas;this.ctx=canvas.getContext('2d');this.data=data;this.onSelect=onSelect;this.yaw=-.36;this.pitch=.76;this.zoom=1;this.auto=false;this.paused=false;this.selected=null;this.hits=[];this.bots=new Map();this.tradePrints=[];this.lastEvent=0;this.time=0;this.reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;this.positions=[];this.resize();this.observer=new ResizeObserver(()=>this.resize());this.observer.observe(canvas);this.bind();this.last=performance.now();this.frame=this.frame.bind(this);requestAnimationFrame(this.frame);}
 resize(){const r=this.canvas.getBoundingClientRect();this.w=r.width;this.h=r.height;const d=Math.min(window.devicePixelRatio||1,2);this.canvas.width=this.w*d;this.canvas.height=this.h*d;this.ctx.setTransform(d,0,0,d,0,0);}
 project(x,y,z){const u=x*Math.cos(this.yaw)-z*Math.sin(this.yaw),d=x*Math.sin(this.yaw)+z*Math.cos(this.yaw),v=y*Math.cos(this.pitch)-d*Math.sin(this.pitch),depth=y*Math.sin(this.pitch)+d*Math.cos(this.pitch);const scale=Math.min(this.w/40,this.h/28)*this.zoom*48/(48-depth);return{x:this.w*.5+u*scale,y:this.h*.44-v*scale,depth,scale};}
 bind(){let down=null;this.canvas.addEventListener('pointerdown',e=>{down={x:e.clientX,y:e.clientY,startX:e.clientX,startY:e.clientY};this.canvas.setPointerCapture(e.pointerId)});this.canvas.addEventListener('pointermove',e=>{const r=this.canvas.getBoundingClientRect();if(down){this.yaw+=(e.clientX-down.x)*.007;this.pitch=Math.max(.3,Math.min(1.28,this.pitch+(e.clientY-down.y)*.004));down.x=e.clientX;down.y=e.clientY;}else{const hit=this.hit(e.clientX-r.left,e.clientY-r.top);this.canvas.style.cursor=hit?'pointer':'grab';}});this.canvas.addEventListener('pointerup',e=>{if(down&&Math.hypot(e.clientX-down.startX,e.clientY-down.startY)<6){const r=this.canvas.getBoundingClientRect(),hit=this.hit(e.clientX-r.left,e.clientY-r.top);if(hit){this.selected=hit.id;this.onSelect(hit.kind,hit.id);}}down=null;});this.canvas.addEventListener('pointercancel',()=>down=null);this.canvas.addEventListener('wheel',e=>{e.preventDefault();this.zoom=Math.max(.65,Math.min(2,this.zoom-e.deltaY*.001))},{passive:false});this.canvas.addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','+','-','='].includes(e.key)){e.preventDefault();if(e.key==='ArrowLeft')this.yaw-=.1;if(e.key==='ArrowRight')this.yaw+=.1;if(e.key==='ArrowUp')this.pitch=Math.min(1.28,this.pitch+.08);if(e.key==='ArrowDown')this.pitch=Math.max(.3,this.pitch-.08);if(e.key==='+'||e.key==='=')this.zoom=Math.min(2,this.zoom+.1);if(e.key==='-')this.zoom=Math.max(.65,this.zoom-.1);}});}
 hit(x,y){return[...this.hits].reverse().find(h=>x>=h.x&&x<=h.x+h.w&&y>=h.y&&y<=h.y+h.h);}
 random(bot){bot.seed=(Math.imul(bot.seed,1664525)+1013904223)>>>0;return bot.seed/4294967296;}
 startWander(bot){const booths=this.positions.length?this.positions:[{x:-12,z:-8},{x:12,z:8}],ranked=booths.map((point,index)=>({point,index,distance:Math.hypot(point.x-bot.x,point.z-bot.z)})).sort((a,b)=>b.distance-a.distance),pool=ranked.slice(0,Math.min(2,ranked.length)),chosen=pool[Math.floor(this.random(bot)*pool.length)]||ranked[0],side=this.random(bot)<.5?-1:1,dx=chosen.point.x-bot.x,dz=chosen.point.z-bot.z,length=Math.max(1,Math.hypot(dx,dz)),bend=(2.2+this.random(bot)*3.2)*side,mid={x:(bot.x+chosen.point.x)/2-dz/length*bend,z:(bot.z+chosen.point.z)/2+dx/length*bend},end={x:chosen.point.x+(this.random(bot)-.5)*2.4,z:chosen.point.z+(this.random(bot)-.5)*2.4};bot.route=[mid,end];bot.routeStep=0;bot.roamBooth=chosen.index;bot.speed=1.15+this.random(bot)*1.75;bot.mode='wander';}
 wanderTarget(bot){if(bot.mode==='directed'){const distance=Math.hypot(bot.tx-bot.x,bot.tz-bot.z);if(distance>.28||this.time<(bot.directedUntil||0))return{x:bot.tx,z:bot.tz};bot.mode='wander';bot.route=null;}if(!bot.route||bot.routeStep>=bot.route.length)this.startWander(bot);let target=bot.route[bot.routeStep];if(Math.hypot(target.x-bot.x,target.z-bot.z)<.28){bot.routeStep++;if(bot.routeStep>=bot.route.length)this.startWander(bot);target=bot.route[bot.routeStep];}return target;}
 poly(points,fill,stroke=null,width=1){const c=this.ctx;c.beginPath();points.forEach((p,i)=>{const q=this.project(...p);i?c.lineTo(q.x,q.y):c.moveTo(q.x,q.y)});c.closePath();c.fillStyle=fill;c.fill();if(stroke){c.strokeStyle=stroke;c.lineWidth=width;c.stroke();}}
 line(points,color,width=1,dash=[]){const c=this.ctx;c.beginPath();points.forEach((p,i)=>{const q=this.project(...p);i?c.lineTo(q.x,q.y):c.moveTo(q.x,q.y)});c.strokeStyle=color;c.lineWidth=width;c.setLineDash(dash);c.stroke();c.setLineDash([]);}
 box(queue,x,y,z,w,h,d,colors,stroke='#35515c'){const p=[[x-w/2,y,z-d/2],[x+w/2,y,z-d/2],[x+w/2,y,z+d/2],[x-w/2,y,z+d/2],[x-w/2,y+h,z-d/2],[x+w/2,y+h,z-d/2],[x+w/2,y+h,z+d/2],[x-w/2,y+h,z+d/2]];const faces=[[0,1,5,4],[1,2,6,5],[2,3,7,6],[3,0,4,7],[4,5,6,7]];faces.forEach((f,i)=>{const points=f.map(k=>p[k]);const depth=points.reduce((a,v)=>a+this.project(...v).depth,0)/4;queue.push({depth,draw:()=>this.poly(points,colors[i%colors.length],stroke,.6)});});}
 prism(queue,x,y,z,r,h,colors,stroke='#35515c'){const bottom=Array.from({length:8},(_,i)=>[x+Math.cos(Math.PI/8+i*Math.PI/4)*r,y,z+Math.sin(Math.PI/8+i*Math.PI/4)*r]),top=bottom.map(([px,,pz])=>[px,y+h,pz]);for(let i=0;i<8;i++){const face=[bottom[i],bottom[(i+1)%8],top[(i+1)%8],top[i]],depth=face.reduce((sum,v)=>sum+this.project(...v).depth,0)/4;queue.push({depth,draw:()=>this.poly(face,colors[i%colors.length],stroke,.6)});}const depth=top.reduce((sum,v)=>sum+this.project(...v).depth,0)/8;queue.push({depth,draw:()=>this.poly(top,colors[colors.length-1],stroke,.7)});}
 update(data,animate=false){this.data=data;const returns=data.instruments.flatMap(x=>x.rows||[]).map(x=>Number(x.total_net_return)).filter(Number.isFinite);this.returnRange=returns.length?{min:Math.min(...returns),max:Math.max(...returns)}:{min:0,max:0};const n=data.instruments.length;if(n===4&&data.instruments.every(x=>x.kind==='family'))this.positions=[{x:-10.5,z:-7},{x:10.5,z:-7},{x:-10.5,z:7},{x:10.5,z:7}];else{const cols=Math.min(Math.max(1,n),6,Math.max(1,Math.ceil(Math.sqrt(n*1.5)))),rows=Math.ceil(n/cols);this.positions=data.instruments.map((_,i)=>({x:cols===1?0:-14+(i%cols)*28/(cols-1),z:rows===1?-6:-8+Math.floor(i/cols)*14/(rows-1)}));}if(!animate)this.lastEvent=data.eventId;this.sync();}
 strategyHeight(value){const number=Number(value),range=this.returnRange||{min:0,max:0};if(!Number.isFinite(number)||number===0)return.1;if(range.max===range.min)return.45;return .1+((number-range.min)/(range.max-range.min))*.9;}
 strategyPosition(family,familyIndex,strategyIndex,time=this.time){const centre=this.positions[familyIndex],rows=family.rows||[],strategy=rows[strategyIndex];if(!centre||!strategy)return null;let seed=2166136261;for(const ch of String(strategy.strategy_id))seed=Math.imul(seed^ch.charCodeAt(0),16777619)>>>0;const unit=n=>((seed>>>(n%17))&1023)/1023,anchorAngle=strategyIndex*2.399963+unit(2)*.8,anchorRadius=2.65+Math.sqrt((strategyIndex+.5)/Math.max(1,rows.length))*2.7+unit(7)*.35,anchorX=Math.cos(anchorAngle)*anchorRadius,anchorZ=Math.sin(anchorAngle)*anchorRadius,phase=unit(11)*Math.PI*2,speed=.32+unit(5)*.28,driftX=.55+unit(13)*.85,driftZ=.55+unit(3)*.85;return{x:centre.x+anchorX+Math.sin(time*speed+phase)*driftX+Math.sin(time*speed*.41+phase*1.7)*.42,z:centre.z+anchorZ+Math.sin(time*speed*.79+phase*2.3)*driftZ+Math.cos(time*speed*.47+phase)*.38};}
 sync(){const active=new Set(this.data.agents.map(a=>a.id));for(const id of this.bots.keys())if(!active.has(id))this.bots.delete(id);
 for(const a of this.data.agents){if(!this.bots.has(a.id)){const n=[...a.id].reduce((v,c)=>(v*31+c.charCodeAt(0))>>>0,0),startX=-17+(n%34),phase=(n%6283)/1000;this.bots.set(a.id,{id:a.id,x:startX,z:10,tx:startX,tz:10,color:MINT,pulse:0,speed:1.8,phase,seed:n||1,route:null,routeStep:0,mode:'wander'});}const bot=this.bots.get(a.id);bot.positionState=a.positionState||'none';bot.netReturn=a.netReturn;bot.color=bot.positionState==='positive'?'#58efa2':bot.positionState==='negative'?'#ff665e':bot.positionState==='flat'?'#a8b7ba':MINT;}
 for(const e of this.data.events.filter(e=>e.id>this.lastEvent)){if((e.type==='BUY'||e.type==='SELL')&&e.price!==undefined)this.tradePrints.push({text:e.type+' · '+e.price,strategy:e.strategy||'',side:e.type,age:0,phase:(Number(e.id)||0)%17});const bot=this.bots.get(e.agent);if(!bot)continue;if(e.type==='QUERY'){bot.tx=0;bot.tz=1.5;bot.pulse=1;bot.mode='directed';bot.directedUntil=this.time+4;bot.route=null;}else if(e.type==='BUY'||e.type==='SELL'||e.type==='MOVE'){const i=this.data.instruments.findIndex(x=>x.id===e.instrument);if(i>=0){let target=null;if((e.type==='BUY'||e.type==='SELL')&&e.strategy){const strategyIndex=(this.data.instruments[i].rows||[]).findIndex(row=>row.strategy_id===e.strategy);if(strategyIndex>=0)target=this.strategyPosition(this.data.instruments[i],i,strategyIndex);}const offset=target?.45:1.8;bot.tx=(target?target.x:this.positions[i].x)+offset;bot.tz=(target?target.z:this.positions[i].z)+offset;bot.pulse=1;bot.speed=e.pace==='slow'?1:e.pace==='fast'?4.1:2.55;bot.mode='directed';bot.directedUntil=this.time+4;bot.route=null;}}}
 this.lastEvent=this.data.eventId;
 }
 label(text,x,y,z,color,size=10,align='center'){const p=this.project(x,y,z),c=this.ctx;c.font=`${size}px Consolas, monospace`;c.textAlign=align;c.fillStyle=color;c.fillText(text,p.x,p.y);}
 drawTradePrints(dt){const c=this.ctx;for(const print of this.tradePrints){print.age+=dt;const progress=Math.min(1,print.age/5.5),p=this.project(Math.sin(print.phase)*1.1,4.2+progress*6.8,Math.cos(print.phase)*.8),alpha=Math.max(0,1-progress);c.save();c.globalAlpha=alpha;c.textAlign='center';c.shadowColor=print.side==='BUY'?MINT:AMBER;c.shadowBlur=18;c.fillStyle=print.side==='BUY'?MINT:AMBER;c.font='700 18px Consolas,monospace';c.fillText(print.text,p.x,p.y);c.shadowBlur=0;c.fillStyle='#d9e8e5';c.font='9px Consolas,monospace';c.fillText(print.strategy,p.x,p.y+15);c.restore();}this.tradePrints=this.tradePrints.filter(print=>print.age<5.5);}
 ground(){const c=this.ctx;this.poly([[-19,-.6,-14],[19,-.6,-14],[19,-.6,14],[-19,-.6,14]],'#071015','#354853');this.poly([[-19,0,-14],[19,0,-14],[19,0,14],[-19,0,14]],'#15262e','#3c5866');this.poly([[-19,0,14],[19,0,14],[19,-.6,14],[-19,-.6,14]],'#101c24','#304853');
 for(let x=-18;x<=18;x+=2)this.line([[x,.01,-14],[x,.01,14]],'#263c46',.45);for(let z=-14;z<=14;z+=2)this.line([[-19,.01,z],[19,.01,z]],'#263c46',.45);
 this.line([[-18,.03,-13],[18,.03,-13],[18,.03,13],[-18,.03,13],[-18,.03,-13]],'#5e8d80',1);
 for(const z of [-4,4]){this.line([[-18,.03,z],[18,.03,z]],'#597d8670',1,[4,7]);}
 this.line([[-19,.04,11],[-15,.04,11]],MINT,3);this.line([[15,.04,11],[19,.04,11]],AMBER,3);
 this.label('ENTRY',-17.1,.1,12.8,'#b5f5d2',8);this.label('EXIT',17,.1,12.8,'#f3b478',8);
 const p=this.project(0,.05,12.5);c.save();c.translate(p.x,p.y);c.fillStyle='#688b9850';c.font='bold 17px Bahnschrift, sans-serif';c.textAlign='center';c.fillText('A G E N T I C   E X C H A N G E',0,0);c.restore();
 }
 drawBooth(queue,x,i){const p=this.positions[i],color=x.availableToBuy?MINT:'#708996';const isSelected=this.selected===x.id;this.box(queue,p.x,.05,p.z,4,.28,3.4,['#1a2d36','#1a3038','#263c42','#192c33','#263d43']);this.box(queue,p.x,.34,p.z,3.35,.65,2.6,['#243e47','#192d36','#2c444c','#1c323a','#35515b']);this.box(queue,p.x,.98,p.z,3.6,.14,2.85,['#365a62','#2d454c','#344d50','#233d45',isSelected?'#74a890':'#416363']);this.box(queue,p.x,1.12,p.z-.55,2.8,1.35,.20,['#0b1b20','#23404a','#101e25','#263d48','#345460']);this.box(queue,p.x,1.13,p.z+.85,2.2,.45,.12,['#0b1b20','#26424d','#132a30','#23414a','#39626a']);
 const panel=[[p.x-1.22,1.28,p.z-.43],[p.x+1.22,1.28,p.z-.43],[p.x+1.22,2.32,p.z-.43],[p.x-1.22,2.32,p.z-.43]];queue.push({depth:this.project(p.x,1.8,p.z-.42).depth+.1,draw:()=>{this.poly(panel,'#102a28',color,.6);this.label(x.displayText||(x.priceText===null?'NO QUOTE':'USD '+x.priceText),p.x,1.85,p.z-.42,color,7);}});
 this.box(queue,p.x,.22,p.z+1.7,2.7,.04,.06,[color],color);
 // Tall corner supports create the silhouette of a physical exchange booth.
 for(const offset of [-1.55,1.55])this.box(queue,p.x+offset,.32,p.z-.9,.09,2.5,.09,['#426571','#304b56']);
 this.box(queue,p.x,2.8,p.z-.9,3.3,.13,.2,['#4a6a73','#314e59','#567985','#2b4650','#6c9995']);
 }
 drawStrategyMarkers(queue,family,index){const rows=family.rows||[];rows.forEach((strategy,i)=>{const point=this.strategyPosition(family,index,i),x=point.x,z=point.z,value=Number(strategy.total_net_return),height=this.strategyHeight(value),color=value>0?'#58efa2':value<0?'#ff665e':'#81949b',records=Array.isArray(strategy.positive_rising_hour_records)?strategy.positive_rising_hour_records:[];this.prism(queue,x,.05,z,.065,height,[color+'b8',color+'8f',color+'d6',color+'78'],color);for(const record of records){const hour=Math.max(0,Math.min(23,Math.floor(Number(record.hour_of_day)))),y=.05+height*((hour+.5)/24);this.prism(queue,x,y,z,.086,Math.min(.034,Math.max(.022,height/32)),['#0758a8','#043f7d','#0b6bc5','#032f60'],'#043f7d');}});}
 drawStickman(queue,bot,id,bob,moving){const walking=!this.reduced&&moving,phase=walking?this.time*6+bot.phase:0,swing=Math.sin(phase)*.34,leftLift=walking?Math.max(0,Math.sin(phase))*.15:0,rightLift=walking?Math.max(0,-Math.sin(phase))*.15:0,x=bot.x,z=bot.z,leanX=walking?(bot.facingX||0)*.1:0,leanZ=walking?(bot.facingZ||0)*.1:0,head=this.project(x+leanX,1.72+bob,z+leanZ),neck=this.project(x+leanX,1.43+bob,z+leanZ),hip=this.project(x,.78+bob,z),leftElbow=this.project(x-.3+leanX,1.18+bob,z+leanZ-swing*.5),rightElbow=this.project(x+.3+leanX,1.18+bob,z+leanZ+swing*.5),leftHand=this.project(x-.48,1.01+bob,z-swing),rightHand=this.project(x+.48,1.01+bob,z+swing),leftKnee=this.project(x-.16,.43+bob+leftLift*.55,z+swing*.55),rightKnee=this.project(x+.16,.43+bob+rightLift*.55,z-swing*.55),leftFoot=this.project(x-.25,.05+leftLift,z+swing),rightFoot=this.project(x+.25,.05+rightLift,z-swing),depth=head.depth,c=this.ctx;queue.push({depth,draw:()=>{c.save();c.strokeStyle=bot.color;c.fillStyle='#102129';c.lineWidth=Math.max(1.6,head.scale*.075);c.lineCap='round';c.lineJoin='round';const segment=(a,b)=>{c.beginPath();c.moveTo(a.x,a.y);c.lineTo(b.x,b.y);c.stroke();};segment(neck,hip);segment(neck,leftElbow);segment(leftElbow,leftHand);segment(neck,rightElbow);segment(rightElbow,rightHand);segment(hip,leftKnee);segment(leftKnee,leftFoot);segment(hip,rightKnee);segment(rightKnee,rightFoot);c.beginPath();c.arc(head.x,head.y,Math.max(4,head.scale*.16),0,Math.PI*2);c.fill();c.stroke();const numeric=Number(bot.netReturn),value=bot.netReturn===null||bot.netReturn===undefined?'N/A':(numeric>=0?'+':'−')+Math.abs(numeric).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2}),shortId=String(id).split('-')[0],tag=shortId+' : '+value;c.font='8px Consolas,monospace';const tagWidth=c.measureText(tag).width+12;c.fillStyle='#071116e8';c.fillRect(head.x-tagWidth/2,head.y-24,tagWidth,14);c.strokeStyle=bot.color;c.lineWidth=1;c.strokeRect(head.x-tagWidth/2,head.y-24,tagWidth,14);c.fillStyle='#e6eeeb';c.textAlign='center';c.fillText(tag,head.x,head.y-14);c.restore();this.hits.push({kind:'agent',id,x:head.x-tagWidth/2,y:head.y-24,w:tagWidth,h:Math.max(48,leftFoot.y-head.y+24)});}});}
 boothLabel(x,i){const p=this.positions[i],q=this.project(p.x,3.45,p.z),c=this.ctx,w=this.w<540?110:136,h=44,left=q.x-w/2,top=q.y-h,color=x.availableToBuy?MINT:'#8aabb8';c.fillStyle=this.selected===x.id?'#203c30f5':'#0c1a20ee';c.strokeStyle=this.selected===x.id?MINT:'#38545d';c.lineWidth=1;c.beginPath();c.roundRect(left,top,w,h,3);c.fill();c.stroke();c.textAlign='left';c.font='10px Bahnschrift,sans-serif';c.fillStyle='#dfebe9';c.fillText(x.name||x.id,left+7,top+13);c.font='9px Consolas,monospace';c.fillStyle=color;c.fillText(x.displayText||(x.priceText===null?'UNPRICED':'USD '+x.priceText),left+7,top+26);c.font='8px Consolas,monospace';c.fillText(x.availabilityLabel,left+7,top+38);this.hits.push({kind:x.kind||'strategy',id:x.id,x:left,y:top,w,h});}
 frame(now){const dt=Math.min((now-this.last)/1000,.05);this.last=now;this.time+=dt;if(!this.w||!this.h||document.hidden){requestAnimationFrame(this.frame);return;}this.sync();if(this.auto&&!this.reduced)this.yaw+=dt*.07;const c=this.ctx;c.clearRect(0,0,this.w,this.h);this.hits=[];this.ground();const queue=[];
 // Intelligence kiosk, used by agents paying for a query.
 this.box(queue,0,.1,0,2,.35,2,['#1a3547','#112c3a','#1e3c4e','#172d3a','#315467']);this.box(queue,0,.45,0,1,2.6,1,['#204256','#1c3648','#2c5265','#162f3d','#7dabbd'],BLUE);
 this.data.instruments.forEach((x,i)=>{if(x.kind==='family')this.drawStrategyMarkers(queue,x,i);this.drawBooth(queue,x,i);});
 for(const [id,b] of this.bots){const desired=this.wanderTarget(b),dx=desired.x-b.x,dz=desired.z-b.z,d=Math.hypot(dx,dz),moving=!this.paused&&!this.reduced&&d>.001;if(!this.paused){if(this.reduced){b.x=desired.x;b.z=desired.z;}else if(moving){const v=Math.min(d,dt*(b.speed||3.4));b.facingX=dx/d;b.facingZ=dz/d;b.x+=b.facingX*v;b.z+=b.facingZ*v;}b.pulse=Math.max(0,b.pulse-dt*.14);}
 const q=this.project(b.x,0,b.z);if(b.pulse>.2&&d>.8){this.line([[b.x,.09,b.z],[b.tx,.09,b.tz]],b.color+'40',1,[2,5]);}c.fillStyle='#050b1090';c.beginPath();c.ellipse(q.x,q.y,q.scale*.38,q.scale*.18,0,0,Math.PI*2);c.fill();const bob=moving?Math.abs(Math.sin(this.time*5.25+b.phase))*.07:0;this.drawStickman(queue,b,id,bob,moving);if(this.selected===id){c.strokeStyle=MINT;c.lineWidth=1.5;c.beginPath();c.ellipse(q.x,q.y,q.scale*.72,q.scale*.34,0,0,Math.PI*2);c.stroke();}
 }
 queue.sort((a,b)=>a.depth-b.depth);for(const item of queue)item.draw();
 this.data.instruments.map((x,i)=>({x,i,depth:this.project(this.positions[i].x,3,this.positions[i].z).depth})).sort((a,b)=>a.depth-b.depth).forEach(({x,i})=>this.boothLabel(x,i));
 this.label('INTELLIGENCE',0,3.6,0,BLUE,this.w<540?6:8);this.label('USD '+this.data.queryFee+' / DELIVERY',0,3.05,0,'#7799ae',this.w<540?5:6);
 this.drawTradePrints(dt);
 requestAnimationFrame(this.frame);}
}
window.ArenaFloor=ArenaFloor;
})();



window.ArenaProjection={
 amount(value){return value===null||value===undefined?null:String(value).replace(/(\.\d*?[1-9])0+$|\.0+$/,'$1');},
 tradeReference(operation,details={}){const value=operation==='SELL'?details.exit_cum_net_return:details.entry_cum_net_return;return value===null||value===undefined?'CUM_NET unavailable':'CUM_NET '+this.amount(value);},
 family(record){const name=(record.descriptive_name||'').toLowerCase();if(name.startsWith('breakout_r_rev'))return'breakout_r_rev';if(name.startsWith('breakout_rev'))return'breakout_rev';if(name.startsWith('breakout_r'))return'breakout_r';return'breakout';},
 families(items){const result={breakout:[],breakout_r:[],breakout_r_rev:[],breakout_rev:[]};for(const item of items)result[this.family(item)].push(item);for(const rows of Object.values(result))rows.sort((a,b)=>Number(b.total_net_return)-Number(a.total_net_return)||a.strategy_id.localeCompare(b.strategy_id));return result;},
 familyBooths(items){const labels={breakout:'Breakout',breakout_r:'Breakout R',breakout_r_rev:'Breakout R Rev',breakout_rev:'Breakout Rev'},groups=this.families(items);return Object.entries(labels).map(([id,name])=>{const rows=groups[id],net=rows.reduce((sum,row)=>sum+Number(row.total_net_return||0),0);return{id:'FAMILY_'+id.toUpperCase(),family:id,kind:'family',name,displayText:(net>=0?'+':'−')+'USD '+Math.abs(net).toLocaleString(undefined,{maximumFractionDigits:0}),availabilityLabel:rows.length+' STRATEGIES',availableToBuy:rows.some(row=>row.available_to_buy),rows,net};});},
 booths(items,mode,search,page,size){const term=search.toLowerCase();const filtered=items.filter(x=>(mode!=='available'||x.available_to_buy===true)&&(x.strategy_id+' '+(x.descriptive_name||'')).toLowerCase().includes(term)).sort((a,b)=>a.strategy_id.localeCompare(b.strategy_id));const pages=Math.max(1,Math.ceil(filtered.length/size));page=Math.min(Math.max(0,page),pages-1);return{page,pages,total:filtered.length,items:filtered.slice(page*size,(page+1)*size).map(x=>({id:x.strategy_id,name:x.descriptive_name||x.strategy_id,priceText:this.amount(x.price?.unit_price),availableToBuy:x.available_to_buy===true,availabilityLabel:!x.valuation_bound?'AWAITING VALUATION':x.available_units===0?'SOLD OUT':x.status!=='active'?'NOT ACTIVE':x.available_units+' UNITS AVAILABLE',record:x}))};}
};
// VERSION HISTORY v3.0.0 · 2026-09-11 · Render every connected agent as an animated labelled stickman.
// v2.9.0 · 2026-09-10 · Keep every connected agent milling perpetually around its current destination.
// v2.8.0 · 2026-09-10 · Render searchable owner audit records with actor, affected party, effect and outcome.
// v2.7.0 · 2026-09-10 · Render connected agents as headed cruciform figures with persistent unique-ID labels.
// v2.6.0 · 2026-09-10 · Increase strategy milling speed and displacement so motion remains visibly continuous.
// v2.5.0 · 2026-09-10 · Administer persistent open/token entry directly from the Arena entry screen.
// v2.4.0 · 2026-09-10 · Give each strategy an irregular market-like milling path around its family booth.
// v2.3.0 · 2026-09-10 · Support server-authorised open Arena entry while preserving protected action APIs.
// v2.2.0 · 2026-09-10 · Replace per-strategy 3D booths with four family booths mapped to the scrolling windows.
// v2.1.0 · 2026-09-10 · Group every directory strategy into four independently scrolling family windows with net return.
// v2.0.3 · 2026-09-02 · Start presence polling on sign-in; invalidate paused polling loops.
// v2.0.0 · 2026-09-02 · Connect reused 3D geometry to read-only API snapshots; retain audit controls and isolate credentials.
// v1.0.1 · 2026-09-02 · Ignore old live-refresh completions after sign-out and use singular event labels.
// v1.1.0 · 2026-09-16 · Both/Buy/Sell selector re-fetches side-only strategy returns for every floor display.
// v1.0.0 · 2026-09-02 · Read-only Arena with instance-scoped cursors, dynamic collections and memory-only authentication.
(()=>{'use strict';
const $=id=>document.getElementById(id),node=(tag,value,cls)=>{const n=document.createElement(tag);n.textContent=value;if(cls)n.className=cls;return n;};
let catalogue=[],connected=[],configuration={},floorPage=0,floorInstance='',selected=null,side='both';
let token='',role='',isAdmin=false,session=0,requestVersion=0,cursor=0,instance='',events=[],filters=new URLSearchParams(),timer=null,live=false,liveVersion=0,pollSeconds=5,publicAccess=false,refreshFailures=0,directorySource='sql';

const floor=new ArenaFloor($('arena-canvas'),{agents:[],instruments:[],events:[],eventId:0,queryFee:'—'},inspect);
$('filter-operation').append(node('option','MOVE'));
function pair(dl,key,value){dl.append(node('dt',key),node('dd',value===null||value===undefined?'Not available':String(value)));}
function netReturn(value){const number=Number(value);if(!Number.isFinite(number))return'Not available';return(number>=0?'+':'−')+'USD '+Math.abs(number).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2});}
function renderFamilies(){const labels={breakout:'Breakout',breakout_r:'Breakout R',breakout_r_rev:'Breakout R Rev',breakout_rev:'Breakout Rev'},groups=ArenaProjection.families(catalogue),root=$('family-windows');root.replaceChildren();for(const family of Object.keys(labels)){const section=node('section','','family-window'),heading=node('div','','family-window-heading'),title=node('h3',labels[family]),count=node('span',groups[family].length+' STRATEGIES');heading.append(title,count);const list=node('div','','family-list');list.setAttribute('tabindex','0');list.setAttribute('aria-label',labels[family]+' strategies');for(const strategy of groups[family]){const button=node('button',''),identity=node('span',''),value=node('strong',netReturn(strategy.total_net_return),Number(strategy.total_net_return)>=0?'positive':'negative');identity.append(node('b',strategy.strategy_id),node('small',strategy.descriptive_name||family));button.append(identity,value);button.type='button';button.onclick=()=>inspect('strategy',strategy.strategy_id);list.append(button);}section.append(heading,list);root.append(section);}}
function inspect(kind,id){selected={kind,id};floor.selected=id;$('floor-inspector').replaceChildren();$('inspect-title').textContent=id;
 const dl=node('dl','');
 if(kind==='strategy'){const x=catalogue.find(x=>x.strategy_id===id),ref=x?.market_reference;if(!x)return;pair(dl,'Strategy',x.descriptive_name||id);if(side==='both')pair(dl,'Cumulative net return',netReturn(ref?.cumulative_net_return??x.total_net_return));else{pair(dl,side.toUpperCase()+'-only net return',netReturn(x.total_net_return));pair(dl,side.toUpperCase()+'-only trades',x.total_trades);pair(dl,'Settlement reference (both sides)',netReturn(ref?.cumulative_net_return));}pair(dl,'Settlement model','Entry/exit cumulative-return movement');pair(dl,'Available units',x.available_units);pair(dl,'Issued units',x.issued_units);pair(dl,'Available to buy',x.available_to_buy?'Yes':'No');pair(dl,'Source status',x.status);pair(dl,'Reference version',ref?.reference_version);pair(dl,'Provenance',ref?.provenance);}
 else if(kind==='family'){const x=ArenaProjection.familyBooths(catalogue).find(x=>x.id===id);if(!x)return;$('inspect-title').textContent=x.name;pair(dl,'Family',x.family);pair(dl,'Strategies',x.rows.length);pair(dl,side==='both'?'Combined net return':side.toUpperCase()+'-only net return',netReturn(x.net));pair(dl,'Profitable strategies',x.rows.filter(row=>Number(row.total_net_return)>0).length);pair(dl,'Window','Use the matching scrolling list above to inspect individual strategies');}
 else if(kind==='agent'){const x=connected.find(x=>x.agent_id===id);pair(dl,'Presence',x?'Present':'Exited');if(x){pair(dl,'Heartbeat',x.heartbeat_healthy?'Healthy':'Awaiting reconnection');pair(dl,'Last seen',new Date(x.last_seen*1000).toLocaleString());pair(dl,'Net return since seed',netReturn(x.agent_net_return));pair(dl,'Account return direction',x.agent_return_state||'unknown');}pair(dl,'Private position details','Available only in the participant workspace');}
 else {const x=events.find(x=>x.event_id===id);if(!x)return;$('inspect-title').textContent=x.operation+' · event '+x.cursor;$('floor-inspector').append(node('pre',JSON.stringify(x,null,2)));return;}
 $('floor-inspector').append(dl);
}
function renderFloor(animate=false){const familyBooths=ArenaProjection.familyBooths(catalogue);
 renderFamilies();
 floor.update({agents:connected.map(a=>({id:a.agent_id,positionState:a.agent_return_state,netReturn:a.agent_net_return})),instruments:familyBooths,events:events.map(e=>({id:e.cursor,agent:e.agent_id,type:e.operation,pace:e.details.pace,price:(e.operation==='BUY'||e.operation==='SELL')?ArenaProjection.tradeReference(e.operation,e.details):undefined,strategy:e.strategy_id,instrument:e.operation==='MOVE'?'FAMILY_'+String(e.details.destination).toUpperCase():'FAMILY_'+ArenaProjection.family(catalogue.find(x=>x.strategy_id===e.strategy_id)||{}).toUpperCase()})),eventId:cursor,queryFee:ArenaProjection.amount(configuration.intelligence_fee)||'—'},animate);
 $('floor-agent-count').textContent=String(connected.length);$('floor-empty').hidden=Boolean(catalogue.length);
 $('booth-list').replaceChildren();for(const x of familyBooths){const b=node('button',x.name+' · '+x.availabilityLabel);b.type='button';b.onclick=()=>inspect('family',x.id);$('booth-list').append(b);}
 $('floor-economics').textContent='MIN '+(configuration.minimum_units??'—')+' WHOLE UNIT · TRADE USD '+(ArenaProjection.amount(configuration.trade_fee)??'—')+' / SETTLEMENT · INTELLIGENCE USD '+(ArenaProjection.amount(configuration.intelligence_fee)??'—')+' / DELIVERY';
 $('floor-feed').replaceChildren();for(const e of [...events].reverse().slice(0,12)){const b=node('button',e.operation+(e.strategy_id?' · '+e.strategy_id:''));b.append(node('small',new Date(e.occurred_at).toLocaleString()+' · '+e.agent_id));b.onclick=()=>inspect('event',e.event_id);$('floor-feed').append(b);}if(!events.length)$('floor-feed').append(node('p','No recorded activity.'));
 if(selected)inspect(selected.kind,selected.id);
}
function viewFloor(show){$('floor-pane').hidden=!show;$('audit-pane').hidden=show;$('show-floor').setAttribute('aria-pressed',String(show));$('show-audit').setAttribute('aria-pressed',String(!show));if(show){floor.resize();renderFloor();}}
$('show-floor').onclick=()=>viewFloor(true);$('show-audit').onclick=()=>viewFloor(false);
$('floor-orbit').onclick=()=>{floor.auto=!floor.auto;$('floor-orbit').setAttribute('aria-pressed',String(floor.auto));};
$('floor-zoom-in').onclick=()=>floor.zoom=Math.min(2,floor.zoom+.15);
$('floor-zoom-out').onclick=()=>floor.zoom=Math.max(.65,floor.zoom-.15);
$('floor-home').onclick=()=>{floor.yaw=-.36;floor.pitch=.76;floor.zoom=1;floor.auto=false;$('floor-orbit').setAttribute('aria-pressed','false');};
window.addEventListener('resize',()=>{if(!$('floor-pane').hidden)renderFloor();});

function status(message,error=false){$('arena-status').textContent=message;$('arena-status').classList.toggle('error',error);}
async function api(path,options={}){const generation=session,headers={...(token?{Authorization:'Bearer '+token}:{}),...(options.body?{'Content-Type':'application/json'}:{}),...options.headers};const response=await fetch(path,{...options,headers});const data=await response.json();if(generation!==session)throw new Error('Previous session discarded');if(!response.ok)throw new Error(typeof data.detail==='string'?data.detail:'API request failed ('+response.status+'). Check filters and credential.');return data;}
async function readEntryPolicy(){try{const response=await fetch('/v1/arena/access-policy'),policy=await response.json();if(!response.ok)throw new Error();publicAccess=policy.public_access;$('arena-public-toggle').checked=publicAccess;$('arena-token-optional').textContent=publicAccess?'(optional)':'';$('arena-entry-note').textContent=publicAccess?'Open entry is enabled. Leave the token blank and select Open Arena.':'Token entry is required. An owner can enable open entry using the switch above.';}catch{$('arena-entry-note').textContent='Entry policy unavailable. Use a valid token.';}try{const response=await fetch('/v1/arena/directory-source'),policy=await response.json();if(!response.ok)throw new Error();directorySource=policy.source;$('arena-directory-source-toggle').checked=directorySource==='pg';$('arena-directory-source-row').hidden=!policy.pg_available;}catch{$('arena-directory-source-row').hidden=true;}}
function stop(){live=false;liveVersion++;clearTimeout(timer);timer=null;refreshFailures=0;$('arena-live').textContent='Start live updates';}
function startLive(immediate=false){stop();live=true;const version=liveVersion;$('arena-live').textContent='Stop live updates';if(immediate)tick(version);else timer=setTimeout(()=>tick(version),pollSeconds*1000);}
function clear(){catalogue=[];connected=[];configuration={};floorPage=0;floorInstance='';selected=null;floor.auto=false;floor.selected=null;floor.bots.clear();floor.update({agents:[],instruments:[],events:[],eventId:0,queryFee:'—'});$('floor-inspector').replaceChildren();$('inspect-title').textContent='Select a booth';for(const id of ['floor-feed','booth-list','family-windows'])$(id).replaceChildren();session++;requestVersion++;stop();token='';role='';isAdmin=false;cursor=0;instance='';events=[];filters=new URLSearchParams();$('arena-filters').reset();for(const id of ['presence','available-inventory','arena-events','enforcement-list'])$(id).replaceChildren();$('presence-count').textContent='0';$('event-count').textContent='';$('event-scope').textContent='';$('arena-asof').textContent='';$('recover-all').hidden=true;$('agent-enforcement').hidden=true;$('arena-workspace').hidden=true;$('arena-access').hidden=false;$('connection-state').textContent='Not connected';$('arena-token').value='';}
async function enforce(agentId,action){const reason=window.prompt('Reason for '+action+'ing this agent:','Administrator action');if(reason===null)return;if(!window.confirm((action==='ban'?'Ban and revoke access for ':'Eject ')+agentId+'?'))return;await api('/v1/admin/agents/'+agentId+'/'+action,{method:'POST',body:JSON.stringify({reason})});await refresh();status(action==='ban'?'Agent banned and credentials revoked.':'Agent ejected. Reconnection is blocked until reinstated.');}
function renderPresence(data){$('presence-count').textContent=String(data.items.length);$('presence').replaceChildren();for(const agent of data.items){const row=node('div','','presence-item');row.append(node('small',agent.agent_id),node('p',(agent.heartbeat_healthy?'Online':'Connection lost')+' · last heartbeat '+new Date(agent.last_seen*1000).toLocaleString()));if(isAdmin){const eject=node('button','Eject'),ban=node('button','Ban');eject.type=ban.type='button';eject.onclick=()=>enforce(agent.agent_id,'eject').catch(error=>status(error.message,true));ban.onclick=()=>enforce(agent.agent_id,'ban').catch(error=>status(error.message,true));row.append(eject,ban);}$('presence').append(row);}if(!data.items.length)$('presence').append(node('p','No agents are present.','empty'));}
function renderEnforcement(data){const root=$('enforcement-list');root.replaceChildren();for(const item of data.items){const row=node('div','','presence-item'),lift=node('button','Reinstate');lift.type='button';lift.onclick=async()=>{if(!window.confirm('Reinstate '+item.agent_id+'?'))return;try{const result=await api('/v1/admin/agents/'+item.agent_id+'/enforcement',{method:'DELETE'});await refresh();status(result.new_credential_required?'Ban lifted. The owner must issue a replacement agent credential.':'Agent reinstated and may reconnect with its existing credential.');}catch(error){status(error.message,true);}};row.append(node('b',item.name),node('small',item.agent_id),node('p',item.status.toUpperCase()+' · '+item.reason),lift);root.append(row);}if(!data.items.length)root.append(node('p','No agents are ejected or banned.','empty'));}
function renderInventory(data){$('available-inventory').replaceChildren();const available=data.items.filter(x=>x.available_to_buy);for(const item of available){const ref=item.market_reference||{};const row=node('div','','inventory-item');row.append(node('p',item.strategy_id),node('p',item.available_units+' units available · '+(side==='both'?'cumulative return '+netReturn(ref.cumulative_net_return??item.total_net_return):side.toUpperCase()+'-only return '+netReturn(item.total_net_return))),node('small',ref.provenance||'Cumulative-return reference'));$('available-inventory').append(row);}if(!available.length)$('available-inventory').append(node('p','No strategies currently available.','empty'));}
function renderEvents(retainedLimit){const opened=new Set([...$('arena-events').querySelectorAll('details[open]')].map(el=>el.dataset.eventId));$('arena-events').replaceChildren();for(const event of [...events].reverse()){
 const d=event.details,article=node('article','','event');article.dataset.operation=event.operation;
 let title=event.operation;
 if(event.operation==='BUY'||event.operation==='SELL')title+=' '+d.units+' '+event.strategy_id+' at '+ArenaProjection.tradeReference(event.operation,d);
 else if(event.operation==='QUERY')title+=' · '+d.kind+' · '+d.result_count+' results ('+d.mode+')';
 else if(event.operation==='REPORT')title+=' · '+d.action+' (not another trade)';
 else if(event.operation==='REJECTED')title+=' · '+(event.strategy_id||'historical strategy unavailable');
 const actor=event.actor||{type:'agent',id:event.agent_id},affected=event.affected||{},meta=node('div','','audit-meta');
 meta.append(node('span','WHO · '+String(actor.type).toUpperCase()+' '+actor.id),node('span','AFFECTED · '+String(affected.type||'arena').toUpperCase()+' '+(affected.id||'—')));
 article.append(node('time',new Date(event.occurred_at).toLocaleString()),node('h3',title),meta,node('p','EFFECT · '+event.effect,'effect'),node('p','OUTCOME · '+event.outcome,'outcome'));
 if(event.operation==='QUERY')article.append(node('p',d.strategy_ids.join(', '),'record'));
 const detail=document.createElement('details');detail.dataset.eventId=event.event_id;detail.open=opened.has(event.event_id);detail.append(node('summary','Inspect event '+event.cursor),node('pre',JSON.stringify(event,null,2)));article.append(detail);$('arena-events').append(article);
 }if(!events.length)$('arena-events').append(node('p','No activity matches these filters.','empty'));$('event-count').textContent=events.length+' EVENT'+(events.length===1?'':'S');$('event-scope').textContent='Latest '+retainedLimit+' matching events · '+(role==='owner'?'owner-scoped comprehensive audit':'public Arena activity')+' · cursor '+cursor+'.';}
async function refresh(reset=false){const version=++requestVersion;
 const config=await api('/v1/exchange');let next=reset||instance!==config.instance_id?0:cursor;let collected=next===0?[]:[...events];
 const requests=[api('/v1/arena/connections'),api('/v1/strategies?availability=all'+(side==='both'?'':'&signal='+side))];if(isAdmin)requests.push(api('/v1/admin/agent-enforcement'));const [presence,inventory,enforcement]=await Promise.all(requests);
 while(true){const params=new URLSearchParams(filters);params.set('after',String(next));params.set('limit',String(config.configuration.activity_page_size));const path=role==='owner'?'/v1/owner/activity-audit':'/v1/arena/activity';const page=await api(path+'?'+params);if(version!==requestVersion)return;collected.push(...page.items);next=page.next_cursor;if(!page.has_more)break;}
 if(version!==requestVersion)return;instance=config.instance_id;cursor=next;pollSeconds=config.configuration.view_poll_seconds;events=[...new Map(collected.map(e=>[e.event_id,e])).values()].sort((a,b)=>a.cursor-b.cursor).slice(-config.configuration.activity_page_size);
 catalogue=inventory.items;$('floor-legend').textContent=(side==='both'?'PILLAR HEIGHT = CUM_NET_RETURN':'PILLAR HEIGHT = '+side.toUpperCase()+'-ONLY NET RETURN')+' · AGENT COLOUR = TOTAL RETURN SINCE SEED';connected=presence.items;configuration=config.configuration;const animate=floorInstance===instance&&!reset;floorInstance=instance;renderPresence(presence);if(enforcement)renderEnforcement(enforcement);renderInventory(inventory);renderEvents(config.configuration.activity_page_size);renderFloor(animate);$('connection-state').textContent='Instance '+instance;$('arena-asof').textContent='Updated '+new Date().toLocaleTimeString()+' · display interval '+pollSeconds+'s';
}
async function tick(version){if(!live||version!==liveVersion)return;const generation=session;let delay=pollSeconds*1000;try{await refresh();if(generation!==session||version!==liveVersion)return;refreshFailures=0;status('Live display updated automatically.');}catch(error){if(generation!==session||version!==liveVersion)return;refreshFailures++;delay=Math.min(30000,pollSeconds*1000*Math.pow(2,Math.min(refreshFailures,3)));status('Live refresh interrupted; retrying automatically. '+error.message,true);}if(live&&version===liveVersion)timer=setTimeout(()=>tick(version),delay);}
$('arena-access').onsubmit=async event=>{event.preventDefault();const button=event.submitter;button.disabled=true;session++;token=$('arena-token').value.trim();try{let identity=null;const desired=$('arena-public-toggle').checked;if(token){identity=await api('/v1/me');role=identity.role;isAdmin=Boolean(identity.is_admin);}if(desired!==publicAccess){if(!identity||identity.role!=='owner')throw new Error('An owner token is required to change Arena entry access.');const policy=await api('/v1/owner/arena-access',{method:'PUT',body:JSON.stringify({public_access:desired})});publicAccess=policy.public_access;}const desiredSource=$('arena-directory-source-toggle').checked?'pg':'sql';if(desiredSource!==directorySource){if(!identity||identity.role!=='owner')throw new Error('An owner token is required to change the directory source.');const sourcePolicy=await api('/v1/owner/directory-source',{method:'PUT',body:JSON.stringify({source:desiredSource})});directorySource=sourcePolicy.source;}if(!token&&!publicAccess)throw new Error('Enter an owner or agent token, or use an owner token to enable Allow entry to all.');await refresh(true);$('arena-token').value='';$('arena-access').hidden=true;$('arena-workspace').hidden=false;$('recover-all').hidden=!isAdmin;$('agent-enforcement').hidden=!isAdmin;viewFloor(true);startLive();status(isAdmin?'Administrator connected. Agent access controls are available.':token?'Connected with a token. Live Arena updates are automatic.':'Entered through open read-only access. Live Arena updates are automatic.');}catch(error){clear();await readEntryPolicy();status(error.message,true);}finally{button.disabled=false;}};
$('arena-refresh').onclick=async()=>{try{await refresh();status('Updated from the API.');}catch(error){status(error.message,true);}};
$('arena-live').onclick=()=>{if(live){stop();status('Live display updates stopped. Agents are unaffected.');}else startLive(true);};
document.addEventListener('visibilitychange',()=>{if(!document.hidden&&live){clearTimeout(timer);timer=null;tick(liveVersion);}});
$('recover-all').onclick=async()=>{const button=$('recover-all');button.disabled=true;try{const result=await api('/v1/admin/recovery',{method:'POST',body:JSON.stringify({request_id:crypto.randomUUID()})});await refresh();status(result.requested_count?('Restart & sync requested for '+result.requested_count+' interrupted agent'+(result.requested_count===1?'':'s')+'. Owner screens will update automatically.'):'All agents and owner channels are already healthy.');}catch(error){status(error.message,true);}finally{button.disabled=false;}};
function setSide(value){side=value;for(const b of document.querySelectorAll('[data-signal]'))b.setAttribute('aria-pressed',String(b.dataset.signal===side));}
for(const b of document.querySelectorAll('[data-signal]'))b.onclick=async()=>{if(b.dataset.signal===side)return;setSide(b.dataset.signal);try{await refresh();status(side==='both'?'Showing both trade sides.':'Showing '+side.toUpperCase()+'-only strategy returns.');}catch(error){status(error.message,true);}};
$('arena-signout').onclick=()=>{setSide('both');clear();status('Signed out. No credential retained.');};
$('arena-filters').onsubmit=async event=>{event.preventDefault();filters=new URLSearchParams();for(const [id,key] of [['filter-agent','agent_id'],['filter-strategy','strategy_id'],['filter-operation','operation']])if($(id).value.trim())filters.set(key,$(id).value.trim());for(const [id,key] of [['filter-from','from'],['filter-to','to']])if($(id).value)filters.set(key,new Date($(id).value).toISOString());try{await refresh(true);status('Activity filters applied.');}catch(error){status(error.message,true);}};
$('clear-filters').onclick=async()=>{$('arena-filters').reset();filters=new URLSearchParams();try{await refresh(true);status('Activity filters cleared.');}catch(error){status(error.message,true);}};
readEntryPolicy();
})();
