const {test}=require('node:test');
const assert=require('node:assert/strict');
const {ArenaEngine,FEE}=require('../engine.js');
const close=(a,b)=>assert.ok(Math.abs(a-b)<1e-8,`${a} != ${b}`);
test('Agents start at exactly $1; participant registration is capped at 10',()=>{const e=new ArenaEngine(1,false);for(let i=0;i<10;i++){const a=e.join(true);close(e.nav(a),1);}assert.equal(e.join(true),null);assert.equal(e.agents.length,10);assert.ok(e.join(false));});
test('Buying and selling units conserves supply and deducts each-way fees',()=>{const e=new ArenaEngine(1,false),a=e.join(),x=e.instruments[0];assert.ok(e.buy(a,x.id,.2));close(a.cash,.7999);close(e.nav(a),1-FEE);close(a.holdings[x.id],20);close(x.available,x.supply-20);assert.ok(e.sell(a,x.id));close(a.cash,1-2*FEE);close(x.available,x.supply);assert.deepEqual(a.holdings,{});});
test('Fully allocated instrument blocks additional buys; sale makes units available',()=>{const e=new ArenaEngine(1,false),a=e.join(),b=e.join(),x=e.instruments[0];x.supply=x.available=80;assert.ok(e.buy(a,x.id,1));close(x.available,0);assert.equal(e.buy(b,x.id,.1),false);assert.ok(e.sell(a,x.id,.5));assert.ok(e.buy(b,x.id,.1));});
test('Intelligence charges reduce cash and NAV and are recorded separately',()=>{const e=new ArenaEngine(1,false),a=e.join();assert.ok(e.query(a));close(a.cash,1-FEE);close(a.queryFees,FEE);close(a.fees,0);assert.equal(a.queries,1);assert.equal(e.events[0].type,'query');e.spend(a,a.cash);assert.equal(e.query(a),false);assert.equal(a.queries,1);});
test('Interest is credited for complete days only and never compounds',()=>{const e=new ArenaEngine(1,false),a=e.join();e.random=()=>.99;e.step(23,false);close(a.interest,0);e.step(1,false);close(a.interest,.03/365);e.step(24,false);close(a.interest,2*.03/365);close(a.cash,1+2*.03/365);});
test('New cash lots wait a full day independently',()=>{const e=new ArenaEngine(1,false),a=e.join();e.random=()=>.99;e.spend(a,.5);e.step(12,false);e.credit(a,.5);e.step(12,false);close(a.interest,.5*.03/365);e.step(12,false);close(a.interest,.03/365);});
test('Flip price applies the opposite per-step return',()=>{const e=new ArenaEngine(1,false);const normal=e.instruments[0],flip=e.instruments.find(x=>x.flip&&x.strategy===0);e.step(3,false);close(normal.price/.01-1,-(flip.price/.01-1));});
test('Exit liquidates and retains agent record; subsequent steps do not alter exited NAV',()=>{const e=new ArenaEngine(1,false),a=e.join();e.buy(a,e.instruments[0].id,.2);assert.ok(e.exit(a));const nav=e.nav(a);e.step(72,false);close(e.nav(a),nav);assert.equal(e.agents.length,1);assert.equal(a.status,'exited');assert.equal(e.buy(a,e.instruments[0].id,.1),false);});
test('Default simulation contains standard and flip purchases and sales',()=>{const e=new ArenaEngine();assert.ok(e.decisions>100);for(const type of ['buy','sell','buy-flip','sell-flip','query'])assert.ok(e.events.some(x=>x.type===type),type);assert.ok(e.stories.length>=3);});
test('Long mixed-regime run maintains cash, holdings and supply invariants',()=>{const e=new ArenaEngine();for(let i=0;i<400;i++){e.regime=['bull','bear','balanced','volatile'][i%4];e.step(3);for(const x of e.instruments){const held=e.agents.reduce((s,a)=>s+(a.holdings[x.id]||0),0);close(held+x.available,x.supply);assert.ok(x.available>=-1e-8);assert.ok(x.price>0);}for(const a of e.agents){assert.ok(a.cash>=-1e-8);assert.ok(Number.isFinite(e.nav(a)));assert.ok(new Set(Object.keys(a.holdings).map(id=>e.instruments.find(x=>x.id===id).strategy)).size<=10);}}});
test('Long-running showcase prices stay within a readable finite domain',()=>{const e=new ArenaEngine();for(let i=0;i<5000;i++)e.step(3,false);for(const x of e.instruments)assert.ok(x.price>=.0002&&x.price<=.05);for(const s of e.strategies)assert.ok(s.index>=.05&&s.index<=5);});
test('Serialized state resumes with identical agents, holdings and RNG',()=>{const e=new ArenaEngine();const restored=ArenaEngine.restore(e.snapshot());assert.equal(restored.snapshot(),e.snapshot());e.step();restored.step();assert.equal(restored.snapshot(),e.snapshot());});
test('Owner read-only command pauses decisions while valuation history continues',()=>{const e=new ArenaEngine(1,false),a=e.join(true);e.buy(a,e.instruments[0].id,.2);e.random=()=>0;const decisions=a.decisions,queries=a.queries,history=a.history.length;assert.ok(e.ownerCommand(a,'read_only').ok);e.step(24,false);assert.equal(a.decisions,decisions);assert.equal(a.queries,queries);assert.equal(a.history.length,history+1);assert.ok(a.interest>0);assert.equal(a.mode,'read-only');assert.ok(e.ownerCommand(a,'participate').ok);assert.equal(a.mode,'full');});
test('Owner messages are retained and rejected for unowned agents',()=>{const e=new ArenaEngine(1,false),mine=e.join(true),other=e.join(false);assert.ok(e.ownerCommand(mine,'message',{text:'Protect liquidity.'}).ok);assert.equal(mine.ownerMessages[0].text,'Protect liquidity.');assert.equal(e.ownerCommand(other,'message',{text:'No'}).ok,false);assert.equal(ArenaEngine.restore(e.snapshot()).agents[0].ownerMessages[0].text,'Protect liquidity.');});
test('Owner can mandate one-position or all-position exits without choosing a purchase',()=>{const e=new ArenaEngine(1,false),a=e.join(true),one=e.instruments[0],two=e.instruments[1];e.buy(a,one.id,.2);e.buy(a,two.id,.2);assert.ok(e.ownerCommand(a,'exit_strategy',{instrument:one.id}).ok);assert.equal(a.holdings[one.id],undefined);assert.ok(a.holdings[two.id]>0);assert.ok(e.ownerCommand(a,'exit_all').ok);assert.deepEqual(a.holdings,{});assert.equal(a.status,'active');});
test('Owner leave command freezes the record and cannot restart the agent',()=>{const e=new ArenaEngine(1,false),a=e.join(true);e.buy(a,e.instruments[0].id,.2);assert.ok(e.ownerCommand(a,'leave').ok);assert.equal(a.status,'exited');assert.equal(e.ownerCommand(a,'participate').ok,false);assert.equal(e.ownerCommand(a,'leave').ok,false);});

const vm = require('node:vm');
const fs = require('node:fs');
const path = require('node:path');
const renderingContext = {window:{}};
vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../floor.js'),'utf8'),renderingContext);
const haze = renderingContext.window.ArenaFloor.performanceHaze;
test('Profit and loss haze use distinct colours and neutral returns have no haze',()=>{
 assert.equal(haze(5).rgb,'79,244,148');
 assert.equal(haze(-5).rgb,'255,77,91');
 assert.equal(haze(0).alpha,0);
 assert.equal(haze(NaN).alpha,0);
});
test('Haze grows with return magnitude and saturates without overpowering the floor',()=>{
 assert.ok(haze(8).alpha>haze(1).alpha);
 assert.ok(haze(-8).radius>haze(-1).radius);
 assert.equal(haze(8).alpha,haze(-8).alpha);
 assert.equal(haze(100).alpha,haze(10).alpha);
 assert.ok(haze(100).alpha<.6);
});
