// VERSION HISTORY v1.7.0 · 2026-09-10 · Verify strategy milling changes position across adjacent animation frames.
// v1.6.0 · 2026-09-10 · Exercise the Arena-local access-policy control during sign-in.
// v1.5.0 · 2026-09-10 · Verify strategy pillars mill irregularly while remaining grouped around family booths.
// v1.4.0 · 2026-09-10 · Verify corner placement and one slowly orbiting signed-return pillar per strategy.
// v1.3.0 · 2026-09-10 · Verify the 3D projection has exactly four family booths with aggregate figures.
// v1.2.0 · 2026-09-10 · Verify exclusive family classification and performance ordering for all strategy windows.
// v1.1.0 · 2026-09-02 · Exercise automatic sign-in polling, presence changes, pause and sign-out.
// v1.0.1 · 2026-09-02 · Verify a single available booth is centred after browser review.
// v1.0.0 · 2026-09-02 · Exercise actual browser projection and renderer event logic without a synthetic trading engine.
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),test=require('node:test'),path=require('node:path');
const source=fs.readFileSync(path.join(__dirname,'../src/lean_exchange/web/arena.js'),'utf8');
const context={window:{}};vm.createContext(context);vm.runInContext(source.split("(()=>{'use strict';")[0],context);
const projection=context.window.ArenaProjection;
const rows=[{strategy_id:'DNA_1',status:'active',price:{unit_price:'1.5000000000'},available_units:550,issued_units:1000,valuation_bound:true,available_to_buy:true},{strategy_id:'DNA_2',status:'active',price:null,available_units:null,issued_units:null,valuation_bound:false,available_to_buy:false},{strategy_id:'DNA_3',status:'active',price:{unit_price:'0.0000000000'},available_units:0,issued_units:10,valuation_bound:true,available_to_buy:false}];
test('catalogue keeps unknown and sold-out explicit; available view excludes both',()=>{const all=projection.booths(rows,'all','',0,24);assert.equal(all.total,3);assert.equal(all.items[0].priceText,'1.5');assert.equal(all.items[1].priceText,null);assert.equal(all.items[1].availabilityLabel,'AWAITING VALUATION');assert.equal(all.items[2].priceText,'0');assert.equal(all.items[2].availabilityLabel,'SOLD OUT');const available=projection.booths(rows,'available','',0,24);assert.equal(available.total,1);assert.equal(available.items[0].id,'DNA_1');});
test('search and pagination clamp without removing source records',()=>{assert.equal(projection.booths(rows,'all','dna_2',9,1).items[0].id,'DNA_2');assert.equal(projection.booths(rows,'all','missing',0,6).total,0);assert.equal(rows.length,3);});
test('strategy families are exclusive and sorted by net return',()=>{const input=[['DNA_1','breakout_2',2],['DNA_2','breakout_r_2',4],['DNA_3','breakout_r_rev_2',1],['DNA_4','breakout_rev_2',3],['DNA_5','BRK-B-DUR-TP',5]].map(([strategy_id,descriptive_name,total_net_return])=>({strategy_id,descriptive_name,total_net_return}));const groups=projection.families(input);assert.deepEqual(Object.fromEntries(Object.entries(groups).map(([key,value])=>[key,Array.from(value,x=>x.strategy_id)])),{breakout:['DNA_5','DNA_1'],breakout_r:['DNA_2'],breakout_r_rev:['DNA_3'],breakout_rev:['DNA_4']});});
test('3D floor projection contains one booth per family',()=>{const input=['breakout','breakout_r','breakout_r_rev','breakout_rev'].map((name,index)=>({strategy_id:'DNA_'+index,descriptive_name:name,total_net_return:index+1,available_to_buy:false}));const booths=projection.familyBooths(input);assert.equal(booths.length,4);assert.deepEqual(Array.from(booths,x=>x.family),['breakout','breakout_r','breakout_r_rev','breakout_rev']);assert.ok(booths.every(x=>x.kind==='family'&&x.rows.length===1));});
test('four family booths occupy equal floor corners',()=>{const floor=Object.create(context.window.ArenaFloor.prototype);floor.bots=new Map();floor.sync=()=>{};floor.update({agents:[],instruments:['a','b','c','d'].map(id=>({id,kind:'family'})),events:[],eventId:0});assert.deepEqual(Array.from(floor.positions,p=>[p.x,p.z]),[[-10.5,-7],[10.5,-7],[-10.5,7],[10.5,7]]);});
test('every strategy gets a continuously moving pillar coloured by net-return sign',()=>{const floor=Object.create(context.window.ArenaFloor.prototype);floor.positions=[{x:-10.5,z:-7}];const calls=[];floor.prism=(queue,x,y,z,r,h,colors)=>calls.push({x,z,color:colors[0]});const family={rows:[{strategy_id:'DNA_1',total_net_return:10},{strategy_id:'DNA_2',total_net_return:-2},{strategy_id:'DNA_3',total_net_return:0}]};floor.time=0;floor.drawStrategyMarkers([],family,0);const first=calls.map(x=>[x.x,x.z]);assert.equal(calls.length,3);assert.ok(calls[0].color.startsWith('#58efa2'));assert.ok(calls[1].color.startsWith('#ff665e'));assert.ok(calls[2].color.startsWith('#81949b'));calls.length=0;floor.time=.05;floor.drawStrategyMarkers([],family,0);assert.ok(calls.every((point,index)=>point.x!==first[index][0]||point.z!==first[index][1]));});
test('one available booth is centred',()=>{const floor=Object.create(context.window.ArenaFloor.prototype);floor.bots=new Map();floor.update({agents:[],instruments:projection.booths(rows,'available','',0,24).items,events:[],eventId:0});assert.equal(floor.positions[0].x,0);assert.equal(floor.positions[0].z,-6);});
test('UUID agents are positioned finitely and only new recorded events move them',()=>{const floor=Object.create(context.window.ArenaFloor.prototype);floor.bots=new Map();floor.lastEvent=0;const id='2e3c683e-4cef-4a70-afa8-b7811405c63d';const data={agents:[{id}],instruments:projection.booths(rows,'all','',0,24).items,events:[{id:10,agent:id,type:'QUERY'}],eventId:10};floor.update(data,false);const bot=floor.bots.get(id);assert.ok(Number.isFinite(bot.x));assert.equal(bot.tz,10);floor.update({...data,events:[...data.events,{id:11,agent:id,type:'QUERY'}],eventId:11},true);assert.equal(bot.tx,0);assert.equal(bot.tz,1.5);floor.update({...data,events:[{id:12,agent:id,type:'BUY',instrument:'DNA_1'}],eventId:12},true);assert.equal(bot.tx,floor.positions[0].x+1.8);floor.update({...data,agents:[],eventId:12},true);assert.equal(floor.bots.size,0);});
test('structured slow MOVE sends the visible agent toward its requested booth',()=>{const floor=Object.create(context.window.ArenaFloor.prototype);floor.bots=new Map();floor.lastEvent=0;const id='0067ff6f-13e3-460a-90a1-c73055aa2a58',instruments=['BREAKOUT','BREAKOUT_R','BREAKOUT_R_REV','BREAKOUT_REV'].map(name=>({id:'FAMILY_'+name,kind:'family'}));floor.update({agents:[{id}],instruments,events:[],eventId:0},false);floor.update({agents:[{id}],instruments,events:[{id:1,agent:id,type:'MOVE',instrument:'FAMILY_BREAKOUT_R',pace:'slow'}],eventId:1},true);const bot=floor.bots.get(id);assert.equal(bot.tx,floor.positions[1].x+1.8);assert.equal(bot.tz,floor.positions[1].z+1.8);assert.equal(bot.speed,1);});
test('connected agents perpetually mill around their current anchor',()=>{const floor=Object.create(context.window.ArenaFloor.prototype),bot={tx:4,tz:-3,phase:1.2};floor.time=0;const first=floor.wanderTarget(bot);const later=floor.wanderTarget(bot,10);assert.notDeepEqual(first,later);assert.ok(Math.abs(first.x-bot.tx)<2&&Math.abs(first.z-bot.tz)<2);assert.ok(Math.abs(later.x-bot.tx)<2&&Math.abs(later.z-bot.tz)<2);});
test('agent renderer exposes an articulated stickman instead of cruciform boxes',()=>{assert.match(source,/drawStickman\(queue,bot,id,bob,moving\)/);assert.match(source,/segment\(neck,leftHand\).*segment\(hip,leftFoot\)/);assert.doesNotMatch(source,/this\.box\(queue,b\.x,\.54\+bob/);});
test('observer contains no trading engine, fake return haze, browser storage or mutation calls',()=>{for(const forbidden of ['localStorage','sessionStorage','.innerHTML','performanceHaze','Math.random','engine.js',"method:'POST'","method:'DELETE'",'$0.0001'])assert.ok(!source.includes(forbidden),forbidden);});

test('sign-in automatically polls connected agents; pause and sign-out cancel polling',async()=>{
 const elements=new Map(),timers=new Map();let timerId=0,agents=[],floor;
 const element=()=>({value:'',checked:false,textContent:'',hidden:false,clientWidth:800,classList:{toggle(){}},append(){},replaceChildren(){},setAttribute(){},querySelectorAll(){return[];},reset(){}});
 const get=id=>{if(!elements.has(id))elements.set(id,element());return elements.get(id);};
 class FloorStub{constructor(){floor=this;this.bots=new Map();}update(data){this.data=data;}resize(){}}
 const sandbox={ArenaFloor:FloorStub,ArenaProjection:projection,URLSearchParams,Map,Set,Date,String,window:{addEventListener(){}},document:{getElementById:get,createElement:element},setTimeout(fn,ms){const id=++timerId;timers.set(id,{fn,ms});return id;},clearTimeout(id){timers.delete(id);},async fetch(url){let data={};if(url==='/v1/me')data={role:'owner'};else if(url==='/v1/arena/access-policy')data={public_access:false,entry_mode:'token_required'};else if(url==='/v1/exchange')data={instance_id:'test',configuration:{view_poll_seconds:5,activity_page_size:100}};else if(url==='/v1/arena/connections')data={items:agents};else if(url.startsWith('/v1/strategies'))data={items:[]};else if(url.startsWith('/v1/arena/activity')||url.startsWith('/v1/owner/activity-audit'))data={items:[],next_cursor:0,has_more:false};return{ok:true,json:async()=>data};}};
 vm.createContext(sandbox);vm.runInContext("(()=>{'use strict';"+source.split("(()=>{'use strict';")[1],sandbox);
 get('arena-token').value='test-only';await get('arena-access').onsubmit({preventDefault(){},submitter:{}});
 assert.equal(get('arena-live').textContent,'Stop live updates');assert.equal(timers.size,1);
 async function poll(){const [id,timer]=timers.entries().next().value;assert.equal(timer.ms,5000);timers.delete(id);await timer.fn();}
 agents=[{agent_id:'external-agent',last_seen:1}];await poll();assert.equal(get('floor-agent-count').textContent,'1');assert.equal(floor.data.agents[0].id,'external-agent');
 agents=[];await poll();assert.equal(get('floor-agent-count').textContent,'0');assert.equal(floor.data.agents.length,0);
 get('arena-live').onclick();assert.equal(timers.size,0);assert.equal(get('arena-live').textContent,'Start live updates');
 get('arena-signout').onclick();assert.equal(timers.size,0);assert.equal(get('arena-workspace').hidden,true);assert.equal(floor.data.agents.length,0);
});
