/**
 * lib/verification/site-generation.ts — generation queue, completion recording,
 * and the preview-notification guard for the web-activation pipeline.
 *
 * VERSION HISTORY
 * v1.1.0 · 2026-07-29 · Replaces the business_claimed + null-URL queue check with
 *   the explicit awaiting_site_generation stage, renames the completion target to
 *   ready_for_preview, and adds getBusinessesReadyForPreviewNotification() so the
 *   cron job can find businesses still owed their preview email.
 * v1.0.0 · 2026-07-29 · Initial version: queue query and recordSiteGenerated(),
 *   deliberately excluding any attempt to invoke generation itself.
 */

import { and, asc, eq, notInArray } from "drizzle-orm";
import { db } from "@/lib/db/client";
import { businesses, pipelineStages, stageTransitions, previewDeliveryMessages } from "@/lib/db/schema";

/**
 * The actual site-generation step is an agent-invoked skill (ep044_group),
 * not something this application can call as a function -- generating a
 * static site means running a Claude skill against the business's data and
 * images. This module deliberately does NOT attempt to trigger that; it
 * only surfaces the queue and records the outcome once generation has
 * actually happened, the same separation of concerns as a work queue and
 * its worker.
 *
 * Stage flow (see migrations/0016_site_generation_queue_stage.sql):
 *   business_claimed -> awaiting_site_generation -> ready_for_preview
 * awaiting_site_generation is set immediately on claim approval
 * (see claims-approval.ts) and is itself the queue signal -- no separate
 * null-check is needed once a business is in that stage.
 */

async function getStageId(key: string): Promise<number | null> {
  const [stage] = await db.select().from(pipelineStages).where(eq(pipelineStages.key, key)).limit(1);
  return stage?.id ?? null;
}

export type BusinessAwaitingGeneration = {
  id: string; businessRef: string; businessName: string; category: string; town: string | null;
  stageEnteredAt: Date | null;
};

/** Businesses queued for site generation -- the actual work a scheduled agent run should consume. */
export async function getBusinessesAwaitingSiteGeneration(): Promise<BusinessAwaitingGeneration[]> {
  const stageId = await getStageId("awaiting_site_generation");
  if (!stageId) return [];
  return db.select({
    id: businesses.id, businessRef: businesses.businessRef, businessName: businesses.businessName,
    category: businesses.category, town: businesses.town, stageEnteredAt: businesses.stageEnteredAt,
  }).from(businesses).where(eq(businesses.currentStageId, stageId)).orderBy(asc(businesses.stageEnteredAt));
}

/**
 * Records that a site has actually been generated and advances the pipeline
 * stage to ready_for_preview. Called only after real generation work has
 * completed -- never speculatively, and never before the site genuinely
 * exists at siteUrl.
 */
export async function recordSiteGenerated(input: {
  businessId: string; siteUrl: string; actorUserId: string;
}) {
  const readyStageId = await getStageId("ready_for_preview");
  if (!readyStageId) throw new Error("The Ready for Preview pipeline stage is unavailable.");

  return db.transaction(async (tx) => {
    const [biz] = await tx.select({ currentStageId: businesses.currentStageId })
      .from(businesses).where(eq(businesses.id, input.businessId));
    if (!biz) throw new Error("Business not found.");

    const now = new Date();
    await tx.update(businesses).set({
      generatedSiteUrl: input.siteUrl, websiteGeneratedAt: now,
      currentStageId: readyStageId, stageEnteredAt: now, lastUpdated: now,
    }).where(eq(businesses.id, input.businessId));

    await tx.insert(stageTransitions).values({
      businessId: input.businessId, fromStageId: biz.currentStageId, toStageId: readyStageId,
      occurredAt: now, source: "automation", actorUserId: input.actorUserId,
      reason: "Site generated by ep044_group skill run",
    });
  });
}

export type BusinessReadyForPreviewNotification = {
  id: string; businessRef: string; businessName: string; email: string | null; generatedSiteUrl: string | null;
};

/**
 * Businesses at ready_for_preview that have never had a preview_ready
 * message prepared. Absence of a preview_delivery_messages row (any status)
 * is the "not yet notified" guard -- avoids re-notifying every watcher cycle
 * without needing a further pipeline stage just to mean "notification sent".
 */
export async function getBusinessesReadyForPreviewNotification(): Promise<BusinessReadyForPreviewNotification[]> {
  const stageId = await getStageId("ready_for_preview");
  if (!stageId) return [];
  const alreadyNotified = await db.selectDistinct({ businessId: previewDeliveryMessages.businessId })
    .from(previewDeliveryMessages).where(eq(previewDeliveryMessages.messageType, "preview_ready"));
  const excludeIds = alreadyNotified.map((row) => row.businessId);
  return db.select({
    id: businesses.id, businessRef: businesses.businessRef, businessName: businesses.businessName,
    email: businesses.email, generatedSiteUrl: businesses.generatedSiteUrl,
  }).from(businesses).where(and(
    eq(businesses.currentStageId, stageId),
    excludeIds.length ? notInArray(businesses.id, excludeIds) : undefined,
  )).orderBy(asc(businesses.stageEnteredAt));
}
