(function(){'use strict';
 const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
 const STORAGE='agentic-arena-demo-v4';let engine,storageOK=true;
 try{const saved=localStorage.getItem(STORAGE);engine=saved?ArenaEngine.restore(saved):new ArenaEngine();}catch{engine=new ArenaEngine();storageOK=false;}
 let running=true,speed=1,lastTick=performance.now(),selected={kind:'strategy',id:'VX-L'},boothFilter='all',moverSort='top',lastFeed=-1,currentStory=null,storyFormat='post';
 const money=(x,d=4)=>'$'+x.toFixed(d),pct=x=>(x>=0?'+':'')+x.toFixed(2)+'%',sign=x=>x>=0?'up':'down';
 const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const time=h=>`DAY ${Math.floor(h/24)+1} · ${String(Math.floor(h%24)).padStart(2,'0')}:00`;
 const floor=new ArenaFloor($('#arena'),engine,select);
 const DIRECTORY='/api/directory/strategies';let directoryRows=[],priorGroups=[];
 async function loadDirectory(){const status=$('#directoryStatus'),mode=$('#directoryGroup').value,count=Number($('#directoryBoothCount').value);status.textContent='Loading live directory…';try{let page=1,items=[],total=Infinity;while(items.length<total){const r=await fetch(`${DIRECTORY}?page=${page}&page_size=100`);if(!r.ok)throw new Error(`Directory ${r.status}`);const b=await r.json();items=items.concat(b.data.items);total=b.data.total;page++;}directoryRows=items;const groups=DirectoryGroups.buildBoothGroups(items,{mode,boothCount:count});const activity=DirectoryGroups.diffBoothActivity(priorGroups,groups);groups.forEach(g=>g.activity=activity[g.id]||null);priorGroups=groups;floor.setDirectoryBooths(groups);const unavailable=groups[0]?.availability==='unavailable';status.textContent=unavailable?'Target attributes are not published by the Directory':`${items.length.toLocaleString()} strategies · ${groups.length} booths · live summary`;$('#boothCount').textContent=groups.length+' directory groups';}catch(err){status.textContent='Directory unavailable — simulated booths remain';floor.setDirectoryBooths(null);}}
 $('#directoryGroup').addEventListener('change',loadDirectory);$('#directoryBoothCount').addEventListener('change',loadDirectory);$('#refreshDirectory').addEventListener('click',loadDirectory);loadDirectory();
 function expandFloor(expand){$('#stage').classList.toggle('expanded',expand);$('#expandFloor').setAttribute('aria-label',expand?'Exit expanded floor':'Expand trading floor');document.body.style.overflow=expand?'hidden':'';}
 $('#expandFloor').addEventListener('click',()=>expandFloor(!$('#stage').classList.contains('expanded')));
 document.addEventListener('keydown',e=>{if(e.key==='Escape')expandFloor(false);});
 $('#regime').value=engine.regime;
 function spark(values,w=86,h=28){const min=Math.min(...values),max=Math.max(...values),range=max-min||.01;const points=values.map((v,i)=>`${(i/(values.length-1||1)*w).toFixed(1)},${(h-3-(v-min)/range*(h-6)).toFixed(1)}`).join(' ');const color=values.at(-1)>=values[0]?'#b5f5d2':'#ed9697';return `<svg class="sparkline" width="${w}" height="${h}" viewBox="0 0 ${w} ${h}" role="img" aria-label="Simulated performance trend"><polyline fill="none" stroke="${color}" stroke-width="1.4" points="${points}"/></svg>`;}
 function save(){try{localStorage.setItem(STORAGE,engine.snapshot());}catch{if(storageOK){storageOK=false;toast('Browser storage unavailable. This demo will not survive a reload.');}}}
 function toast(text){$('#toast').textContent=text;$('#toast').classList.add('visible');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').classList.remove('visible'),4000);}
 function showTab(inspect){$('#activityPanel').hidden=inspect;$('#inspector').hidden=!inspect;$('#activityTab').classList.toggle('active',!inspect);$('#inspectTab').classList.toggle('active',inspect);if(inspect)renderInspector();}
 function select(kind,id){expandFloor(false);selected={kind,id};floor.selected=id;showTab(true);renderBooths();if(innerWidth<851)$('#inspector').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'nearest'});}
 function renderInspector(){const el=$('#inspector');if(selected.kind==='agent'){
  const a=engine.agents.find(a=>a.id===selected.id);if(!a)return;const nav=engine.nav(a),ret=engine.ret(a),keys=Object.keys(a.holdings),cashPercent=a.cash/nav*100;
  el.innerHTML=`<div class="inspect-kicker">PARTICIPANT-OWNED AGENT ${a.owned?'· YOUR AGENT':''}</div><div class="inspect-heading"><h2>${a.name}</h2><span class="inspect-badge">${a.status==='exited'?'EXITED':'AUTONOMOUS'}</span></div><p class="inspect-description">${a.personality} · ${Math.floor(((a.exited??engine.hour)-a.created)/24)} days of simulated history</p><div class="inspect-nav">${money(nav)}</div><div class="inspect-change ${sign(ret)}">${pct(ret)} <span class="neutral">from $1.0000</span></div><div class="inspect-chart">${spark(a.history,230,64)}</div><div class="inspect-grid"><div><small>Cash allocation</small><b>${cashPercent.toFixed(1)}%</b></div><div><small>Strategy families</small><b>${new Set(keys.map(id=>engine.instruments.find(x=>x.id===id).strategy)).size} / 10</b></div><div><small>Allocation fees</small><b>${money(a.fees)}</b></div><div><small>Intelligence fees</small><b>${money(a.queryFees)}</b></div><div><small>Cash interest</small><b>${money(a.interest,6)}</b></div><div><small>Positive steps*</small><b>${engine.consistency(a).toFixed(1)}%</b></div></div><div class="holdings"><h3>PORTFOLIO ALLOCATION</h3>${keys.map(id=>{const x=engine.instruments.find(x=>x.id===id),v=a.holdings[id]*x.price/nav*100;return `<div class="holding-row"><div><button class="strategy-link" data-inspect-strategy="${id}">${x.name} ↗</button><span>${v.toFixed(1)}%</span></div><div class="bar"><i style="width:${v}%;background:${x.flip?'var(--amber)':'var(--mint)'}"></i></div></div>`}).join('')}<div class="holding-row"><div><span>CASH</span><span>${cashPercent.toFixed(1)}%</span></div><div class="bar"><i style="width:${cashPercent}%;background:#7b919b"></i></div></div></div><div class="inspector-action"><b>Latest decision</b><br>${a.last}<br><br>*Positive or flat simulation steps. Descriptive consistency only, not verified skill. Owners cannot select purchases or allocations; governed safety exits remain available in Owner View.</div>`;
 }else{const x=engine.instruments.find(x=>x.id===selected.id);if(!x)return;const s=engine.strategies[x.strategy],ret=(x.price/.01-1)*100,held=x.supply-x.available,holders=engine.agents.filter(a=>(a.holdings[x.id]||0)>0);
  el.innerHTML=`<div class="inspect-kicker">DIRECTORY BOOTH / ${x.id}</div><div class="inspect-heading"><h2>${x.name}</h2><span class="inspect-badge ${x.flip?'flip':''}">${x.flip?'FLIP':'STRATEGY'}</span></div><p class="inspect-description">${s.family} · ${x.flip?'Inverse exposure · demo assumption':'Standard strategy units'}</p><div class="inspect-nav">${money(x.price,5)}</div><div class="inspect-change ${sign(ret)}">${pct(ret)} <span class="neutral">unit performance</span></div><div class="inspect-chart">${spark(x.history,230,64)}</div><div class="inspect-grid"><div><small>Units available</small><b>${x.available<.001?'SOLD OUT':x.available.toFixed(2)}</b></div><div><small>Total issued</small><b>${x.supply} units</b></div><div><small>Agent holders</small><b>${holders.length}</b></div><div><small>Allocation fee</small><b>$0.0001 each way</b></div></div><div class="holdings"><h3>${(held/x.supply*100).toFixed(1)}% ALLOCATED</h3><div class="bar"><i style="width:${held/x.supply*100}%"></i></div><p class="inspect-description">${x.available<.001?'All units are held. Further allocation is closed.':'Agents can autonomously purchase the remaining units.'}</p><h3>AGENTS HOLDING THIS STRATEGY</h3>${holders.slice(0,5).map(a=>`<div class="holding-row"><div><button class="agent-link" data-inspect-agent="${a.id}">${a.name} ↗</button><span>${a.holdings[x.id].toFixed(2)} units</span></div></div>`).join('')||'<p class="inspect-description">No current holders.</p>'}</div><div class="inspector-action">Strategy intelligence costs the agent $0.0001 per query. Browsing this demo inspector is free.<br><br>${x.flip?'Flip unit value moves by the negative of each strategy return step; inverse results are path-dependent.':'Unit value changes with strategy performance, not with demand.'}</div>`;
 }
 }
 function renderFeed(){if(lastFeed===engine.eventId)return;lastFeed=engine.eventId;const symbols={join:'↳',buy:'↗','buy-flip':'⇄',sell:'↙','sell-flip':'⇄',query:'⌕',exit:'↪','sold-out':'■'};$('#activityFeed').innerHTML=engine.events.slice(0,22).map(e=>`<button class="event ${e.type.includes('flip')?'flip':e.type}" data-event-agent="${e.agent||''}" ${e.agent?'':'disabled'}><span class="event-icon">${symbols[e.type]||'·'}</span><span><strong>${e.name}</strong><p>${escape(e.text)}</p><time>${time(e.hour)}${e.fee?' · FEE '+money(e.fee):''}</time></span></button>`).join('');}
 function renderBooths(){const xs=engine.instruments.filter(x=>boothFilter==='all'||(boothFilter==='flip'?x.flip:!x.flip));$('#boothStrip').innerHTML=xs.map(x=>{const ret=(x.price/.01-1)*100,available=x.available>.001;return `<button class="booth-button ${floor.selected===x.id?'selected':''} ${available?'':'soldout'}" data-booth="${x.id}" aria-label="Inspect ${x.name}"><div class="booth-top"><strong>${x.name}</strong><span class="${x.flip?'flip':''}">${x.flip?'⇄':'↗'}</span></div><div class="booth-value"><span>${money(x.price,5)}</span><span class="${sign(ret)}">${pct(ret)}</span></div><div class="booth-supply"><span>${available?x.available.toFixed(1)+' units left':'SOLD OUT'}</span><span>${x.supply} TOTAL</span></div><div class="bar"><i style="width:${100*(1-x.available/x.supply)}%;${x.flip?'background:var(--amber)':''}"></i></div></button>`}).join('');}
 function renderTables(){const sort=$('#agentSort').value;let agents=sort==='owned'?engine.agents.filter(a=>a.owned):[...engine.agents];if(sort==='consistency')agents.sort((a,b)=>engine.consistency(b)-engine.consistency(a));else if(sort==='drawdown')agents.sort((a,b)=>a.drawdown-b.drawdown);else agents.sort((a,b)=>engine.ret(b)-engine.ret(a));$('#rankingNote').textContent=sort==='consistency'?'Ranked by positive or flat steps · descriptive, not verified skill':sort==='drawdown'?'Ranked by lowest observed maximum drawdown · age varies':sort==='owned'?'Your agents · maximum 10 · no manual portfolio control':'Individual agents · lifetime return · after all fees';
  $('#agentsTable').innerHTML=agents.slice(0,5).map((a,i)=>`<tr><td class="rank-number">${String(i+1).padStart(2,'0')}</td><td><button class="agent-link agent-name" data-table-agent="${a.id}">${a.name}${a.owned?' <span class="up">·</span>':''}<small>${sort==='consistency'?engine.consistency(a).toFixed(1)+'% positive steps':sort==='drawdown'?(a.drawdown*100).toFixed(2)+'% max drawdown':a.personality} · ${a.status==='exited'?'Exited':Math.floor((engine.hour-a.created)/24)+'d'}</small></button></td><td>${money(engine.nav(a))}</td><td class="${sign(engine.ret(a))}">${pct(engine.ret(a))}</td><td>${spark(a.history)}</td></tr>`).join('');
  const xs=[...engine.instruments].sort((a,b)=>moverSort==='top'?b.price-a.price:a.price-b.price);$('#strategiesTable').innerHTML=xs.slice(0,5).map(x=>`<tr><td><button class="strategy-link agent-name" data-table-strategy="${x.id}">${x.name}<small>${engine.strategies[x.strategy].family}${x.flip?' · Inverse':''}</small></button></td><td>${money(x.price,5)}</td><td class="${sign(x.price/.01-1)}">${pct((x.price/.01-1)*100)}</td><td class="${x.available<.001?'down':'neutral'}">${x.available<.001?'SOLD OUT':x.available.toFixed(1)+' left'}</td></tr>`).join('');$('#ownerCount').textContent=engine.agents.filter(a=>a.owned).length+' / 10 owned';
 }
 function renderStories(){const selectedStories=engine.stories.slice(0,3);$('#storyGrid').innerHTML=selectedStories.map(s=>`<article class="story"><div class="story-kicker"><span>${s.kind}</span><span>${time(s.hour).split(' · ')[0]}</span></div><h3>${escape(s.title)}</h3><p>${escape(s.body)}</p><button data-story="${s.id}">Open story draft <span>↗</span></button></article>`).join('');}
 function render(){ $('#day').textContent=time(engine.hour);$('#activeCount').textContent=engine.activeAgents().length;$('#decisionCount').textContent=engine.decisions.toLocaleString();$('#queryCount').textContent=engine.totalQueries.toLocaleString();$('#boothCount').textContent=engine.instruments.filter(x=>x.available>.001).length+' / '+engine.instruments.length;renderFeed();renderTables();renderBooths();renderStories();if(!$('#inspector').hidden)renderInspector();}
 function deploy(){const a=engine.join(true);if(!a){toast('Maximum 10 agents per participant. Existing records are retained.');return;}floor.sync();select('agent',a.id);render();save();toast(a.name+' entered with $1.0000. Its decisions are autonomous.');$('#floor').scrollIntoView({behavior:'smooth',block:'start'});}
 $('#deploy').addEventListener('click',deploy);$('#deployBottom').addEventListener('click',deploy);
 $('#pause').addEventListener('click',()=>{running=!running;floor.paused=!running;$('#pause').innerHTML=running?'Ⅱ <span>Pause</span>':'▷ <span>Resume</span>';$('#pause').setAttribute('aria-label',running?'Pause simulation':'Resume simulation');lastTick=performance.now();save();});
 $('#speed').addEventListener('change',e=>speed=Number(e.target.value));$('#regime').addEventListener('change',e=>{engine.regime=e.target.value;engine.record('regime',null,null,`Demo market changed to ${e.target.value}`);engine.story(`A ${e.target.value} market begins.`,`The demo regime changed on ${time(engine.hour).toLowerCase()}. Watch how autonomous agents adjust their exposure.`,'REGIME WATCH');render();save();toast('Demo regime changed. Agents decide how to respond.');});
 $('#orbit').addEventListener('click',()=>{if(floor.reduced){toast('Automatic orbit is disabled by your reduced-motion preference.');return;}floor.auto=!floor.auto;$('#orbit').setAttribute('aria-pressed',String(floor.auto));});$('#zoomIn').addEventListener('click',()=>floor.zoom=Math.min(2,floor.zoom+.15));$('#zoomOut').addEventListener('click',()=>floor.zoom=Math.max(.65,floor.zoom-.15));$('#homeView').addEventListener('click',()=>{floor.yaw=-.36;floor.pitch=.76;floor.zoom=1;});
 $('#activityTab').addEventListener('click',()=>showTab(false));$('#inspectTab').addEventListener('click',()=>showTab(true));$('#agentSort').addEventListener('change',renderTables);
 $('#boothFilters').addEventListener('click',e=>{const b=e.target.closest('[data-filter]');if(!b)return;boothFilter=b.dataset.filter;$$('#boothFilters button').forEach(x=>x.classList.toggle('active',x===b));renderBooths();});$('#moverFilters').addEventListener('click',e=>{const b=e.target.closest('[data-sort]');if(!b)return;moverSort=b.dataset.sort;$$('#moverFilters button').forEach(x=>x.classList.toggle('active',x===b));renderTables();});
 document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;for(const key of ['booth','tableStrategy','inspectStrategy'])if(b.dataset[key])select('strategy',b.dataset[key]);for(const key of ['eventAgent','tableAgent','inspectAgent'])if(b.dataset[key])select('agent',b.dataset[key]);if(b.hasAttribute('data-rules'))$('#rulesDialog').showModal();if(b.classList.contains('close-dialog'))b.closest('dialog').close();if(b.classList.contains('close-rules'))$('#rulesDialog').close();if(b.dataset.story){currentStory=engine.stories.find(s=>s.id===b.dataset.story);if(currentStory){storyFormat='post';renderDraft();$('#storyDialog').showModal();}}});
 function renderDraft(){const s=currentStory;if(!s)return;const ending='Interactive demo · Simulated performance · No real money.\nExplore the Agentic Trading Arena. Your agent. Its decisions.';$('#storyTitle').textContent=s.title;$('#storyDraft').value=storyFormat==='post'?`${s.title}\n\n${s.body}\n\n${ending}`:`00–05s · HOOK\n${s.title}\n\n05–15s · ON THE FLOOR\nShow the agent activity and strategy booth at ${time(s.hour)}.\n${s.body}\n\n15–25s · WHY IT MATTERS\nAgents choose their exposure autonomously. Every allocation and intelligence query has a cost.\n\n25–35s · INVITATION\n${ending}\n\nON-SCREEN THROUGHOUT: SIMULATED PERFORMANCE`;$$('#storyFormats button').forEach(b=>b.classList.toggle('active',b.dataset.format===storyFormat));}
 $('#storyFormats').addEventListener('click',e=>{const b=e.target.closest('[data-format]');if(b){storyFormat=b.dataset.format;renderDraft();}});
 $('#copyStory').addEventListener('click',async()=>{try{await navigator.clipboard.writeText($('#storyDraft').value);toast('Draft copied. Simulation disclosure included.');}catch{$('#storyDraft').focus();$('#storyDraft').select();toast('Select and copy the draft using your keyboard.');}});
 $('#downloadStory').addEventListener('click',()=>{const blob=new Blob([$('#storyDraft').value],{type:'text/plain;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=aSafeFilename('arena-story-'+storyFormat+'.txt');a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
 function aSafeFilename(s){return s.replace(/[^a-z0-9.-]/gi,'-');}
 $('#generateStory').addEventListener('click',()=>{const top=[...engine.agents].sort((a,b)=>engine.ret(b)-engine.ret(a))[0],best=[...engine.instruments].sort((a,b)=>b.price-a.price)[0];engine.story(`${top.name} takes the spotlight.`,`${pct(engine.ret(top))} from a $1 start. ${best.name} leads unit performance at ${pct((best.price/.01-1)*100)}. Across the Arena: ${engine.decisions.toLocaleString()} allocation decisions and ${engine.totalQueries.toLocaleString()} paid intelligence queries.`,'FLOOR REPORT');renderStories();save();toast('Floor report generated from the current demo state.');});
 for(const d of $$('dialog'))d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close();}});
 document.addEventListener('visibilitychange',()=>{lastTick=performance.now();if(document.hidden)save();});window.addEventListener('pagehide',save);
 setInterval(()=>{const now=performance.now();if(running&&!document.hidden&&now-lastTick>=1800/speed){lastTick=now;engine.step(3);render();save();}},150);
 render();save();if(!storageOK)toast('Demo started. Browser storage was unavailable or could not be restored.');
})();
