/* Perspective-projected 3D geometry, rendered locally without external libraries.
 * VERSION HISTORY
 * v1.1.0 · 2026-08-28 · Adds return-based green/red agent haze; existing renderer predates this history.
 */
(function(){'use strict';
const MINT='#b5f5d2',AMBER='#f3b478',BLUE='#8dc8e9';
class ArenaFloor{
 static performanceHaze(returnPct){const strength=Math.min(1,Math.sqrt(Math.abs(returnPct)/10));return{rgb:returnPct>=0?'79,244,148':'255,77,91',strength,alpha:Number.isFinite(returnPct)&&Math.abs(returnPct)>.001?.12+.42*strength:0,radius:.85+1.15*strength};}
 agentHaze(queue,bot,agent){const appearance=ArenaFloor.performanceHaze(this.engine.ret(agent));if(!appearance.alpha)return;const ground=this.project(bot.x,.04,bot.z),center=this.project(bot.x,.6,bot.z),c=this.ctx,r=ground.scale*appearance.radius;
  // A pool of light follows the agent on the floor; the soft volume is depth sorted.
  const glow=(x,y,rx,ry,opacity)=>{c.save();c.translate(x,y);c.scale(rx,ry);const gradient=c.createRadialGradient(0,0,0,0,0,1);gradient.addColorStop(0,`rgba(${appearance.rgb},${opacity})`);gradient.addColorStop(.35,`rgba(${appearance.rgb},${opacity*.65})`);gradient.addColorStop(1,`rgba(${appearance.rgb},0)`);c.fillStyle=gradient;c.beginPath();c.arc(0,0,1,0,Math.PI*2);c.fill();c.restore();};
  glow(ground.x,ground.y,r*1.35,r*.62,appearance.alpha);
  queue.push({depth:center.depth-.3,draw:()=>glow(center.x,center.y,r*.85,r*1.15,appearance.alpha*.65)});
 }
 constructor(canvas,engine,onSelect){this.canvas=canvas;this.ctx=canvas.getContext('2d');this.engine=engine;this.onSelect=onSelect;this.yaw=-.36;this.pitch=.76;this.zoom=1;this.auto=false;this.paused=false;this.selected=null;this.hits=[];this.bots=new Map();this.lastEvent=0;this.time=0;this.directoryBooths=null;this.reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;this.positions=Array.from({length:48},(_,i)=>({x:[-15,-9,-3,3,9,15][i%6],z:[-8,-2,4,10][Math.floor(i/6)]}));this.resize();new ResizeObserver(()=>this.resize()).observe(canvas);this.bind();this.last=performance.now();this.frame=this.frame.bind(this);requestAnimationFrame(this.frame);}
 setDirectoryBooths(groups){this.directoryBooths=groups;if(!groups?.length){this.directoryPositions=null;return;}const grid=DirectoryGroups.uniformGrid(groups.length),{columns,rows}=grid,xStep=30/Math.max(1,columns-1),zStep=18/Math.max(1,rows-1);this.directoryPositions=groups.map((_,i)=>({x:-15+(i%columns)*xStep,z:-8+Math.floor(i/columns)*zStep}));}
 resize(){const r=this.canvas.getBoundingClientRect();this.w=r.width;this.h=r.height;const d=Math.min(window.devicePixelRatio||1,2);this.canvas.width=this.w*d;this.canvas.height=this.h*d;this.ctx.setTransform(d,0,0,d,0,0);}
 project(x,y,z){const u=x*Math.cos(this.yaw)-z*Math.sin(this.yaw),d=x*Math.sin(this.yaw)+z*Math.cos(this.yaw),v=y*Math.cos(this.pitch)-d*Math.sin(this.pitch),depth=y*Math.sin(this.pitch)+d*Math.cos(this.pitch);const scale=Math.min(this.w/40,this.h/28)*this.zoom*48/(48-depth);return{x:this.w*.5+u*scale,y:this.h*.44-v*scale,depth,scale};}
 bind(){let down=null;this.canvas.addEventListener('pointerdown',e=>{down={x:e.clientX,y:e.clientY,startX:e.clientX,startY:e.clientY};this.canvas.setPointerCapture(e.pointerId)});this.canvas.addEventListener('pointermove',e=>{const r=this.canvas.getBoundingClientRect();if(down){this.yaw+=(e.clientX-down.x)*.007;this.pitch=Math.max(.3,Math.min(1.28,this.pitch+(e.clientY-down.y)*.004));down.x=e.clientX;down.y=e.clientY;}else{const hit=this.hit(e.clientX-r.left,e.clientY-r.top);this.canvas.style.cursor=hit?'pointer':'grab';}});this.canvas.addEventListener('pointerup',e=>{if(down&&Math.hypot(e.clientX-down.startX,e.clientY-down.startY)<6){const r=this.canvas.getBoundingClientRect(),hit=this.hit(e.clientX-r.left,e.clientY-r.top);if(hit){this.selected=hit.id;this.onSelect(hit.kind,hit.id);}}down=null;});this.canvas.addEventListener('pointercancel',()=>down=null);this.canvas.addEventListener('wheel',e=>{e.preventDefault();this.zoom=Math.max(.65,Math.min(2,this.zoom-e.deltaY*.001))},{passive:false});this.canvas.addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','+','-','='].includes(e.key)){e.preventDefault();if(e.key==='ArrowLeft')this.yaw-=.1;if(e.key==='ArrowRight')this.yaw+=.1;if(e.key==='ArrowUp')this.pitch=Math.min(1.28,this.pitch+.08);if(e.key==='ArrowDown')this.pitch=Math.max(.3,this.pitch-.08);if(e.key==='+'||e.key==='=')this.zoom=Math.min(2,this.zoom+.1);if(e.key==='-')this.zoom=Math.max(.65,this.zoom-.1);}});}
 hit(x,y){return[...this.hits].reverse().find(h=>x>=h.x&&x<=h.x+h.w&&y>=h.y&&y<=h.y+h.h);}
 poly(points,fill,stroke=null,width=1){const c=this.ctx;c.beginPath();points.forEach((p,i)=>{const q=this.project(...p);i?c.lineTo(q.x,q.y):c.moveTo(q.x,q.y)});c.closePath();c.fillStyle=fill;c.fill();if(stroke){c.strokeStyle=stroke;c.lineWidth=width;c.stroke();}}
 line(points,color,width=1,dash=[]){const c=this.ctx;c.beginPath();points.forEach((p,i)=>{const q=this.project(...p);i?c.lineTo(q.x,q.y):c.moveTo(q.x,q.y)});c.strokeStyle=color;c.lineWidth=width;c.setLineDash(dash);c.stroke();c.setLineDash([]);}
 box(queue,x,y,z,w,h,d,colors,stroke='#35515c'){const p=[[x-w/2,y,z-d/2],[x+w/2,y,z-d/2],[x+w/2,y,z+d/2],[x-w/2,y,z+d/2],[x-w/2,y+h,z-d/2],[x+w/2,y+h,z-d/2],[x+w/2,y+h,z+d/2],[x-w/2,y+h,z+d/2]];const faces=[[0,1,5,4],[1,2,6,5],[2,3,7,6],[3,0,4,7],[4,5,6,7]];faces.forEach((f,i)=>{const points=f.map(k=>p[k]);const depth=points.reduce((a,v)=>a+this.project(...v).depth,0)/4;queue.push({depth,draw:()=>this.poly(points,colors[i%colors.length],stroke,.6)});});}
 prism(queue,x,y,z,r,h,colors,stroke='#35515c'){const bottom=Array.from({length:8},(_,i)=>[x+Math.cos(Math.PI/8+i*Math.PI/4)*r,y,z+Math.sin(Math.PI/8+i*Math.PI/4)*r]),top=bottom.map(([px,,pz])=>[px,y+h,pz]);for(let i=0;i<8;i++){const face=[bottom[i],bottom[(i+1)%8],top[(i+1)%8],top[i]],depth=face.reduce((sum,v)=>sum+this.project(...v).depth,0)/4;queue.push({depth,draw:()=>this.poly(face,colors[i%colors.length],stroke,.6)});}const depth=top.reduce((sum,v)=>sum+this.project(...v).depth,0)/8;queue.push({depth,draw:()=>this.poly(top,colors[colors.length-1],stroke,.7)});}
 sync(){for(const a of this.engine.agents){if(!this.bots.has(a.id)){const n=Number(a.id.split('-')[1]);this.bots.set(a.id,{id:a.id,x:this.lastEvent?-19:((n*7.31)%32)-16,z:this.lastEvent?11:((n*3.79)%22)-11,tx:((n*8.3)%32)-16,tz:((n*5.71)%22)-11,color:a.owned?MINT:'#708e9d',pulse:0,exit:false});}}
  const events=this.engine.events.filter(e=>e.id>this.lastEvent).reverse();for(const e of events){const bot=this.bots.get(e.agent);if(!bot)continue;if(e.type==='exit'){bot.tx=21;bot.tz=11;bot.exit=true;bot.color='#8597a0';}else if(e.type==='query'){bot.tx=0;bot.tz=-1;bot.color=BLUE;bot.pulse=1;}else if(e.instrument){const i=this.engine.instruments.findIndex(x=>x.id===e.instrument);if(i>=0){bot.tx=this.positions[i].x+(e.id%2?2.2:-2.2);bot.tz=this.positions[i].z+1.4;bot.color=e.type.includes('flip')?AMBER:MINT;bot.pulse=1;}}}
  this.lastEvent=this.engine.eventId;
 }
 label(text,x,y,z,color,size=10,align='center'){const p=this.project(x,y,z),c=this.ctx;c.font=`${size}px Consolas, monospace`;c.textAlign=align;c.fillStyle=color;c.fillText(text,p.x,p.y);}
 ground(){const c=this.ctx;this.poly([[-19,-.6,-14],[19,-.6,-14],[19,-.6,14],[-19,-.6,14]],'#071015','#354853');this.poly([[-19,0,-14],[19,0,-14],[19,0,14],[-19,0,14]],'#15262e','#3c5866');this.poly([[-19,0,14],[19,0,14],[19,-.6,14],[-19,-.6,14]],'#101c24','#304853');
 for(let x=-18;x<=18;x+=2)this.line([[x,.01,-14],[x,.01,14]],'#263c46',.45);for(let z=-14;z<=14;z+=2)this.line([[-19,.01,z],[19,.01,z]],'#263c46',.45);
 this.line([[-18,.03,-13],[18,.03,-13],[18,.03,13],[-18,.03,13],[-18,.03,-13]],'#5e8d80',1);
 for(const z of [-4,4]){this.line([[-18,.03,z],[18,.03,z]],'#597d8670',1,[4,7]);}
 this.line([[-19,.04,11],[-15,.04,11]],MINT,3);this.line([[15,.04,11],[19,.04,11]],AMBER,3);
 this.label('ENTRY',-17.1,.1,12.8,'#b5f5d2',8);this.label('EXIT',17,.1,12.8,'#f3b478',8);
 const p=this.project(0,.05,12.5);c.save();c.translate(p.x,p.y);c.fillStyle='#688b9850';c.font='bold 17px Bahnschrift, sans-serif';c.textAlign='center';c.fillText('A G E N T I C   E X C H A N G E',0,0);c.restore();
 }
 drawBooth(queue,x,i){const p=this.positions[i],color=x.flip?AMBER:MINT;const isSelected=this.selected===x.id;this.box(queue,p.x,.05,p.z,4,.28,3.4,['#1a2d36','#1a3038','#263c42','#192c33','#263d43']);this.box(queue,p.x,.34,p.z,3.35,.65,2.6,['#243e47','#192d36','#2c444c','#1c323a','#35515b']);this.box(queue,p.x,.98,p.z,3.6,.14,2.85,['#365a62','#2d454c','#344d50','#233d45',isSelected?'#74a890':'#416363']);this.box(queue,p.x,1.12,p.z-.55,2.8,1.35,.20,['#0b1b20','#23404a','#101e25','#263d48','#345460']);this.box(queue,p.x,1.13,p.z+.85,2.2,.45,.12,['#0b1b20','#26424d','#132a30','#23414a','#39626a']);
 const panel=[[p.x-1.22,1.28,p.z-.43],[p.x+1.22,1.28,p.z-.43],[p.x+1.22,2.32,p.z-.43],[p.x-1.22,2.32,p.z-.43]];queue.push({depth:this.project(p.x,1.8,p.z-.42).depth+.1,draw:()=>{this.poly(panel,'#102a28',color,.6);const samples=x.history.slice(-20),lo=Math.min(...samples),hi=Math.max(...samples),range=hi-lo||.001;this.line(samples.map((v,j)=>[p.x-1.06+j/(samples.length-1||1)*2.12,1.43+(v-lo)/range*.73,p.z-.42]),color,1.4);}});
 this.box(queue,p.x,.22,p.z+1.7,2.7,.04,.06,[color],color);
 // Tall corner supports create the silhouette of a physical exchange booth.
 for(const offset of [-1.55,1.55])this.box(queue,p.x+offset,.32,p.z-.9,.09,2.5,.09,['#426571','#304b56']);
 this.box(queue,p.x,2.8,p.z-.9,3.3,.13,.2,['#4a6a73','#314e59','#567985','#2b4650','#6c9995']);
 }
 drawDirectoryBooth(queue,g,i){const p=(this.directoryPositions||this.positions)[i],h=g.towerHeight||1.1,color=g.activity?.kind==='loss'?'#ed9697':g.activity?.kind==='profit'?MINT:'#8dc8e9',closed=g.closedNetReturn??g.totalNetReturn??0,open=g.openNetReturn??0,weight=Math.abs(closed)+Math.abs(open),closedHeight=weight?h*Math.abs(closed)/weight:h,openHeight=Math.max(0,h-closedHeight),closedColor=closed>=0?'#26765d':'#8c3846',openColor=open>=0?'#61c795':'#d86675';this.prism(queue,p.x,.04,p.z,1.12,closedHeight,[closedColor,'#163a38','#1d4e43','#112c2e','#2f735e'],closedColor);if(openHeight>.02)this.prism(queue,p.x,.04+closedHeight,p.z,1.12,openHeight,[openColor,'#1b4e42','#255e4d','#163b37','#57a985'],openColor);this.prism(queue,p.x,h+.04,p.z,1.20,.15,[color],color);this.box(queue,p.x,h+.19,p.z,.06,1.18,.06,['#8da8b0','#48636b']);const flag=[[p.x+.02,h+.46,p.z-.04],[p.x+1.76,h+.46,p.z-.04],[p.x+1.76,h+1.69,p.z-.04],[p.x+.02,h+1.69,p.z-.04]];queue.push({depth:this.project(p.x+.89,h+1.07,p.z-.04).depth+.2,draw:()=>{this.poly(flag,'#102d34',color,.8);const fq=this.project(p.x+.89,h+1.09,p.z-.06),fc=this.ctx;fc.textAlign='center';fc.font='bold 10px Bahnschrift,sans-serif';fc.fillStyle='#f2fff8';fc.fillText((g.flagLabel||g.label).slice(0,15),fq.x,fq.y+3);}});queue.push({depth:this.project(p.x,.04+h*.5,p.z-.83).depth+.3,draw:()=>{const fc=this.ctx,fmt=n=>`${n>=0?'+':''}${Number(n).toFixed(1)}`;fc.textAlign='center';fc.font='6px Consolas,monospace';const cq=this.project(p.x,.04+closedHeight*.5,p.z-.84);fc.fillStyle='#d7f7e6';fc.fillText(`CLOSED ${fmt(closed)}`,cq.x,cq.y);if(openHeight>.02){const oq=this.project(p.x,.04+closedHeight+openHeight*.5,p.z-.84);fc.fillStyle='#e2fff0';fc.fillText(`OPEN ${fmt(open)}`,oq.x,oq.y);}}});if(g.activeRank){const r=1.8+Math.sin(this.time*4+i)*.12;const pts=Array.from({length:21},(_,n)=>[p.x+Math.cos(n/20*Math.PI*2)*r,.10,p.z+Math.sin(n/20*Math.PI*2)*r]);this.line(pts,color,1.8);}if(g.activity&&!this.reduced){const r=2.1+Math.sin(this.time*9)*.35;const pts=Array.from({length:21},(_,n)=>[p.x+Math.cos(n/20*Math.PI*2)*r,.08,p.z+Math.sin(n/20*Math.PI*2)*r]);this.line(pts,color,2.4);}const q=this.project(p.x,h+.35,p.z),c=this.ctx,number=String(i+1).padStart(2,'0');c.textAlign='center';c.font='7px Consolas,monospace';c.fillStyle='#8dc8e9';c.fillText(`GROUP ${number}`,q.x,q.y-10);c.font='bold 9px Bahnschrift,sans-serif';c.fillStyle='#e9efec';c.fillText(g.label.slice(0,18),q.x,q.y);c.font='7px Consolas,monospace';c.fillStyle=color;c.fillText(`${g.strategyCount} STRAT · ${g.totalTrades} TRADES`,q.x,q.y+10);this.hits.push({kind:'directory',id:g.id,x:q.x-58,y:q.y-20,w:116,h:34});}
 boothLabel(x,i){const p=this.positions[i],q=this.project(p.x,3.25,p.z),c=this.ctx;const mobile=this.w<540;const scale=mobile?.9:Math.max(.85,Math.min(1.05,q.scale/19));const w=(mobile?53:111)*scale,h=(mobile?28:38)*scale,left=q.x-w/2,top=q.y-h;const selected=this.selected===x.id;const color=x.flip?AMBER:MINT;c.fillStyle=selected?'#203c30f5':'#0c1a20ee';c.strokeStyle=selected?color:'#38545d';c.lineWidth=selected?1.4:.7;c.beginPath();c.roundRect(left,top,w,h,3);c.fill();c.stroke();c.textAlign='left';c.font=`${9*scale}px Bahnschrift, sans-serif`;c.fillStyle='#dfebe9';c.fillText(mobile?x.id:x.name,left+7*scale,top+12*scale);const ret=(x.price/.01-1)*100;c.font=`${9*scale}px Consolas, monospace`;c.fillStyle=ret>=0?MINT:'#ed9697';c.fillText(`${ret>=0?'+':''}${ret.toFixed(1)}%`,left+7*scale,top+(mobile?23:25)*scale);c.textAlign='right';c.fillStyle=x.available<.001?AMBER:'#809ca5';c.font=`${7*scale}px Consolas, monospace`;if(!mobile)c.fillText(x.available<.001?'SOLD OUT':`${Math.ceil(x.available)} LEFT`,left+w-7*scale,top+25*scale);c.fillStyle='#30474c';if(!mobile)c.fillRect(left+7*scale,top+h-5*scale,w-14*scale,1.5);c.fillStyle=color;if(!mobile)c.fillRect(left+7*scale,top+h-5*scale,(w-14*scale)*(1-x.available/x.supply),1.5);this.hits.push({kind:'strategy',id:x.id,x:left,y:top,w,h});}
 frame(now){const dt=Math.min((now-this.last)/1000,.05);this.last=now;this.time+=dt;this.sync();if(this.auto&&!this.reduced)this.yaw+=dt*.07;const c=this.ctx;c.clearRect(0,0,this.w,this.h);this.hits=[];this.ground();const queue=[];
 // Intelligence kiosk, used by agents paying for a query.
 this.box(queue,0,.1,0,2,.35,2,['#1a3547','#112c3a','#1e3c4e','#172d3a','#315467']);this.box(queue,0,.45,0,1,2.6,1,['#204256','#1c3648','#2c5265','#162f3d','#7dabbd'],BLUE);
 if(this.directoryBooths)this.directoryBooths.forEach((g,i)=>this.drawDirectoryBooth(queue,g,i));else this.engine.instruments.forEach((x,i)=>this.drawBooth(queue,x,i));
 for(const [id,b] of this.bots){const agent=this.engine.agents.find(a=>a.id===id);if(agent.status==='exited'&&!b.exit){b.exit=true;b.tx=21;b.tz=11;}if(b.exit&&b.x>19.5)continue;const dx=b.tx-b.x,dz=b.tz-b.z,d=Math.hypot(dx,dz);if(!this.paused){if(this.reduced){b.x=b.tx;b.z=b.tz;}else if(d>.08){const v=Math.min(d,dt*3.4);b.x+=dx/d*v;b.z+=dz/d*v;}b.pulse=Math.max(0,b.pulse-dt*.14);}
 this.agentHaze(queue,b,agent);const q=this.project(b.x,0,b.z);if(b.pulse>.2&&d>.8){this.line([[b.x,.09,b.z],[b.tx,.09,b.tz]],b.color+'40',1,[2,5]);}c.fillStyle='#050b1090';c.beginPath();c.ellipse(q.x,q.y,q.scale*.33,q.scale*.15,0,0,Math.PI*2);c.fill();const bob=!this.reduced&&d>.1&&!this.paused?Math.sin(this.time*12+q.x)*.035:0;this.box(queue,b.x,.08+bob,b.z,.32,.53,.25,['#365569','#2b4656',b.color,'#365566','#8eafbd'],'#496371');this.box(queue,b.x,.66+bob,b.z,.27,.25,.25,[b.color,'#476372',b.color,'#476372',b.color],'#486873');const head=this.project(b.x,1,b.z);this.hits.push({kind:'agent',id,x:head.x-7,y:head.y-3,w:14,h:23});if(this.selected===id){c.strokeStyle=MINT;c.lineWidth=1.5;c.beginPath();c.ellipse(q.x,q.y,q.scale*.65,q.scale*.3,0,0,Math.PI*2);c.stroke();}
 }
 queue.sort((a,b)=>a.depth-b.depth);for(const item of queue)item.draw();
 if(!this.directoryBooths)this.engine.instruments.map((x,i)=>({x,i,depth:this.project(this.positions[i].x,3,this.positions[i].z).depth})).sort((a,b)=>a.depth-b.depth).forEach(({x,i})=>this.boothLabel(x,i));
 this.label('INTELLIGENCE',0,3.6,0,BLUE,this.w<540?6:8);this.label('$0.0001 / QUERY',0,3.05,0,'#7799ae',this.w<540?5:6);
 requestAnimationFrame(this.frame);}
}
window.ArenaFloor=ArenaFloor;
})();
