/* owner.js — live participant portfolio view and governed command channel. */
(function(){
 'use strict';
 const STORE='agentic-arena-demo-v4';
 const $=s=>document.querySelector(s), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const money=v=>'$'+v.toFixed(4), pct=v=>(v>=0?'+':'')+v.toFixed(2)+'%', ago=h=>h<1?'now':h<24?`${h}h ago`:`${Math.floor(h/24)}d ago`;
 let engine, selected, pending=null, timer, toastTimer;
 function load(){try{engine=ArenaEngine.restore(localStorage.getItem(STORE));}catch(_){engine=new ArenaEngine();}let xs=engine.agents.filter(a=>a.owned);if(!xs.length)xs=[engine.join(true)];selected=xs.find(a=>a.id===localStorage.getItem('agentic-owner-selected'))?.id||xs[0].id;save();}
 function save(){localStorage.setItem(STORE,engine.snapshot());}
 function owned(){return engine.agents.filter(a=>a.owned)}
 function agent(){return engine.agents.find(a=>a.id===selected)||owned()[0]}
 function spark(values,color='#4ff494',fill=true){if(values.length<2)return'';const w=600,h=130,min=Math.min(...values),max=Math.max(...values),range=max-min||1;const pts=values.map((v,i)=>`${i*w/(values.length-1)},${h-8-(v-min)/range*(h-20)}`).join(' '),area=`0,${h} ${pts} ${w},${h}`;return `<svg viewBox="0 0 ${w} ${h}" preserveAspectRatio="none" role="img" aria-label="Performance history"><defs><linearGradient id="fade" x1="0" y1="0" x2="0" y2="1"><stop stop-color="${color}" stop-opacity=".28"/><stop offset="1" stop-color="${color}" stop-opacity="0"/></linearGradient></defs>${fill?`<polygon points="${area}" fill="url(#fade)"/>`:''}<polyline points="${pts}" fill="none" stroke="${color}" stroke-width="2" vector-effect="non-scaling-stroke"/></svg>`}
 function combinedHistory(xs){const n=Math.max(...xs.map(a=>a.history.length));return Array.from({length:n},(_,i)=>{const vals=xs.map(a=>a.history[a.history.length-n+i]).filter(Number.isFinite);return vals.reduce((s,v)=>s+v,0);});}
 function status(a){return a.status==='exited'?'EXITED':a.mode==='read-only'?'READ-ONLY':'FULL'}
 function bestTime(a){let best={hour:0,gain:-Infinity};for(let i=1;i<a.history.length;i++){const hour=((engine.hour-(a.history.length-1-i)*3)%24+24)%24,g=a.history[i]-a.history[i-1];if(g>best.gain)best={hour,gain:g};}return `${String(best.hour).padStart(2,'0')}:00–${String((best.hour+3)%24).padStart(2,'0')}:00`}
 function render(){const mine=owned(),a=agent();if(!a)return;const nav=mine.reduce((s,x)=>s+engine.nav(x),0),ret=(nav-mine.length)/mine.length*100;$('#portfolioNav').textContent=money(nav);$('#portfolioReturn').textContent=pct(ret);$('#portfolioReturn').className=ret>=0?'up':'down';$('#combinedReturn').textContent=pct(ret);$('#combinedReturn').className=ret>=0?'up':'down';$('#liveTime').textContent=`Arena hour ${engine.hour} · simulated live record`;$('#stableCount').textContent=mine.length;$('#addAgent').disabled=mine.length>=10;
  const all=[...engine.agents].sort((x,y)=>engine.ret(y)-engine.ret(x)),avg=mine.reduce((s,x)=>s+engine.ret(x),0)/mine.length,below=all.filter(x=>engine.ret(x)<=avg).length;$('#portfolioPercentile').textContent=Math.round(100*below/all.length)+'th';$('#agentsProfitable').textContent=mine.filter(x=>engine.ret(x)>0).length+' / '+mine.length;$('#portfolioChart').innerHTML=spark(combinedHistory(mine),ret>=0?'#4ff494':'#ff5f69');
  $('#agentStable').innerHTML=mine.map(x=>{const r=engine.ret(x),alpha=Math.min(.5,.12+Math.abs(r)/35),haze=r>=0?`rgba(79,244,148,${alpha})`:`rgba(255,95,105,${alpha})`;return `<button class="agent-card ${x.id===selected?'selected':''}" data-agent="${x.id}" style="--haze:${haze}"><span class="agent-card-head"><b>${esc(x.name)}</b><span class="status ${x.status==='exited'?'exited':x.mode==='read-only'?'read-only':''}">${status(x)}</span></span><strong>${money(engine.nav(x))}</strong><em class="${r>=0?'up':'down'}">${pct(r)}</em><span class="agent-card-foot"><span>${x.decisions} decisions</span><span>${Object.keys(x.holdings).length} strategies</span></span></button>`}).join('');
  const topStrats=[...engine.strategies].sort((x,y)=>y.index-x.index).slice(0,3);$('#arenaPulse').innerHTML=topStrats.map((s,i)=>`<div class="pulse-row"><div><b>0${i+1} · ${esc(s.name)}</b><span class="${s.index>=1?'up':'down'}">${pct((s.index-1)*100)}</span></div><small>${esc(s.family)} · Directory unit performance</small></div>`).join('');
  const arank=all.findIndex(x=>x.id===a.id)+1,r=engine.ret(a);$('#agentName').textContent=a.name;$('#agentIdentity').textContent=`${a.personality} · active since Arena hour ${a.created}`;$('#agentSigil').textContent=a.name.replace(/[^A-Z0-9]/g,'').slice(0,2);$('#modeBadge').textContent=status(a);$('#modeBadge').className='mode-badge '+(r>=0?'up':'down');$('#agentNav').textContent=money(engine.nav(a));$('#agentReturn').textContent=pct(r);$('#agentReturn').className=r>=0?'up':'down';$('#agentRank').textContent=`#${arank} of ${all.length} agents by return`;$('#agentChart').innerHTML=spark(a.history,r>=0?'#4ff494':'#ff5f69',false);
  const recorded=engine.events.filter(e=>e.agent===a.id),buys=recorded.filter(e=>e.type==='buy'||e.type==='buy-flip').length,sells=recorded.filter(e=>e.type==='sell'||e.type==='sell-flip').length;$('#metricGrid').innerHTML=[['Allocation decisions',a.decisions,'Agent ledger'],['Profitable periods',engine.consistency(a).toFixed(0)+'%','3-hour observations'],['Best time',bestTime(a),'Highest net change'],['Recent buys',buys,'Recorded activity'],['Recent sells',sells,'Recorded activity'],['Directory queries',a.queries,money(a.queryFees)+' cost']].map(x=>`<div class="metric"><span>${x[0]}</span><strong>${x[1]}</strong><small>${x[2]}</small></div>`).join('');
  const holdings=Object.entries(a.holdings).sort(([,q1],[,q2])=>q2-q1);$('#cashAllocation').textContent=`${(100*a.cash/engine.nav(a)).toFixed(1)}% cash`;$('#strategyReturns').innerHTML=holdings.length?holdings.map(([id,q])=>{const x=engine.instruments.find(i=>i.id===id),value=q*x.price,sr=(x.price/.01-1)*100;return `<div class="strategy-row"><b>${esc(x.name)}<small>${q.toFixed(2)} units</small></b><span>${money(value)}</span><span class="${sr>=0?'up':'down'}">${pct(sr)}</span></div>`}).join(''):'<p class="empty-state">No strategy positions. Capital is held as cash.</p>';
  $('#agentActivity').innerHTML=recorded.slice(0,7).map(e=>`<div class="tape-row ${e.type}"><span class="tape-icon">${e.type.includes('buy')?'↗':e.type.includes('sell')?'↙':e.type==='query'?'?':'◆'}</span><div><b>${esc(e.type.replaceAll('-',' ').toUpperCase())}</b><p>${esc(e.text)}</p></div><time>${ago(engine.hour-e.hour)}</time></div>`).join('')||'<p class="empty-state">No recorded activity yet.</p>';
  $('#newsGrid').innerHTML=engine.stories.slice(0,3).map(s=>`<article class="news-card"><span>${esc(s.kind)} <time>${ago(engine.hour-s.hour)}</time></span><h3>${esc(s.title)}</h3><p>${esc(s.body)}</p><button onclick="location.href='index.html#stories'">Open floor broadcast ↗</button></article>`).join('');$('#messageAgent').textContent=a.name;$('#controlAgent').textContent=`Commands will be recorded against ${a.name}.`;
  document.querySelectorAll('[data-agent]').forEach(b=>b.onclick=()=>{selected=b.dataset.agent;localStorage.setItem('agentic-owner-selected',selected);render();$('#agentDetail').scrollIntoView({behavior:'smooth'});});
 }
 function toast(msg,bad=false){const t=$('#ownerToast');t.textContent=msg;t.style.background=bad?'#ff9aa0':'#a9f5cc';t.classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove('visible'),2600)}
 function openConfirm(type){const a=agent(),copy={read_only:'Pause new autonomous decisions and place this agent in read-only mode?',participate:'Resume full autonomous research and portfolio participation?',exit_strategy:'Liquidate one current strategy holding under your safety mandate?',exit_all:'Liquidate every current strategy holding and move the proceeds to cash?',leave:'Exit all positions and leave the Arena? This permanent record cannot be restarted.'};pending=type;$('#confirmText').textContent=copy[type];const label=$('#strategyLabel'),select=$('#strategySelect');label.hidden=type!=='exit_strategy';if(type==='exit_strategy'){select.innerHTML=Object.keys(a.holdings).map(id=>{const x=engine.instruments.find(i=>i.id===id);return `<option value="${id}">${esc(x.name)} · ${a.holdings[id].toFixed(2)} units</option>`}).join('');if(!select.options.length){toast('This agent has no strategies to exit.',true);return;}}$('#controlDialog').close();$('#confirmDialog').showModal();}
 function command(type,payload={}){const result=engine.ownerCommand(agent(),type,payload);if(result.ok){save();render();toast(result.message)}else toast(result.message,true);return result.ok}
 function bind(){$('#addAgent').onclick=()=>{const a=engine.join(true);if(!a)return toast('The 10-agent owner limit has been reached.',true);selected=a.id;save();render();toast(`${a.name} joined the Arena with $1.0000.`)};$('#openMessage').onclick=()=>$('#messageDialog').showModal();$('#openControls').onclick=()=>$('#controlDialog').showModal();document.querySelectorAll('.dialog-close').forEach(b=>b.onclick=()=>b.closest('dialog').close());$('#ownerMessage').oninput=e=>$('#messageCount').textContent=`${e.target.value.length} / 280`;$('#sendMessage').onclick=()=>{if(command('message',{text:$('#ownerMessage').value})){$('#ownerMessage').value='';$('#messageCount').textContent='0 / 280';$('#messageDialog').close();}};document.querySelectorAll('[data-command]').forEach(b=>b.onclick=()=>openConfirm(b.dataset.command));$('#cancelCommand').onclick=()=>{$('#confirmDialog').close();pending=null};$('#confirmCommand').onclick=()=>{const payload=pending==='exit_strategy'?{instrument:$('#strategySelect').value}:{};if(command(pending,payload))$('#confirmDialog').close();pending=null};window.addEventListener('storage',e=>{if(e.key===STORE){try{engine=ArenaEngine.restore(e.newValue);render()}catch(_){}}});}
 function tick(){engine.step(3,true);save();render()}
 load();bind();render();timer=setInterval(tick,2200);document.addEventListener('visibilitychange',()=>{if(document.hidden)clearInterval(timer);else{clearInterval(timer);timer=setInterval(tick,2200);render();}});
})();
