-- Create the leads_pain_points table in Supabase
-- Run this in the Supabase SQL Editor

CREATE TABLE IF NOT EXISTS public.leads_pain_points (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT NOT NULL,
    page_id TEXT NOT NULL,
    pain_point_key TEXT,
    ip_address TEXT,
    captured_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable Row Level Security
ALTER TABLE public.leads_pain_points ENABLE ROW LEVEL SECURITY;

-- Create a policy that allows anyone to INSERT
CREATE POLICY "Allow public insert" ON public.leads_pain_points
    FOR INSERT 
    WITH CHECK (true);

-- Create a policy that prevents anyone from SELECTing, UPDATING, or DELETEing
-- (Unless they are the service_role or authenticated, depending on your needs.
-- For this landing page use-case, we want it private.)
CREATE POLICY "Disallow public select" ON public.leads_pain_points
    FOR SELECT 
    USING (false);

-- Grant permissions to the anon role (used by the browser)
GRANT INSERT ON public.leads_pain_points TO anon;
GRANT USAGE ON SEQUENCE leads_pain_points_id_seq TO anon;
