# epics/ep_058_strategy_intelligence_pg/hosted_directory/app/dashboard_queries.py — vendored query builders.
#
# GENERATED by sync/vendor_dashboard_queries.py from ep_057 dashboards_and_uis/top10_live_server.py (v1.8.0).
# Do not edit by hand; re-run the script (or --check for drift).
"""Query builders behind the Top10 5-min equity curve dashboard (live_day, portfolio_day, similar_strategies,
strategy_catalog, model_trades, hourly_family_report). Reads PostgreSQL tradedb via DSN (set by dashboard_api.install)."""
from __future__ import annotations

import datetime as dt
import json
import os
import re
import time

import psycopg2



COLORS = [
    "#38bdf8", "#34d399", "#f472b6", "#fbbf24", "#a78bfa",
    "#fb923c", "#2dd4bf", "#4ade80", "#e879f9", "#f87171",
]

# Per-model stats for one trading date; strategy/tp from the canonical model definition
STATS_SQL = """
    WITH bounds AS (SELECT %s::date AS day)
    SELECT c.model,
           ROUND(SUM(c.net_return)::numeric, 2) AS total_net,
           ROUND(SUM(c.alt_net_return)::numeric, 2) AS total_alt_net,
           COUNT(*) AS total_trades,
           COUNT(*) FILTER (WHERE c.net_return > 0) AS wins,
           COUNT(*) FILTER (WHERE c.net_return <= 0) AS losses,
           ROUND((COUNT(*) FILTER (WHERE c.net_return > 0)::numeric / COUNT(*)::numeric * 100), 1) AS win_rate,
           COUNT(*) FILTER (WHERE c.alt_net_return > 0) AS alt_wins,
           ROUND((COUNT(*) FILTER (WHERE c.alt_net_return > 0)::numeric / COUNT(*)::numeric * 100), 1) AS alt_win_rate,
           MAX(TRIM(c.product)) AS product,
           COALESCE(MAX(TRIM(pf.strategy_name)), MAX(TRIM(c.strategy_name))) AS strategy,
           MAX(pf.target_profit) AS target_profit,
           MAX(LOWER(TRIM(c.product_type))) AS product_type
    FROM combined_trades_closed c
    CROSS JOIN bounds b
    LEFT JOIN product_forex pf ON TRIM(pf.model) = c.model
    WHERE c.created >= b.day
      AND c.created < b.day + INTERVAL '1 day'
      AND (%s = 'all' OR LOWER(TRIM(c.product_type)) = %s)
      AND (%s = 'all' OR LOWER(TRIM(c.product)) = %s)
    GROUP BY c.model;
"""

PRODUCTS_SQL = """
    SELECT DISTINCT LOWER(TRIM(product)) AS product
    FROM product_forex
    WHERE product IS NOT NULL
      AND (%s = 'all' OR LOWER(TRIM(product_type)) = %s)
    ORDER BY product;
"""

SNAP_SQL = """
    WITH bounds AS (SELECT %s::date AS day)
    SELECT model,
           to_char(snapshot_timestamp, 'HH24:MI') AS time_str,
           ROUND(cum_net::numeric, 1), ROUND(cum_buy_net::numeric, 1), ROUND(cum_sell_net::numeric, 1),
           ROUND(cum_alt_net::numeric, 1), ROUND(cum_buy_alt_net::numeric, 1), ROUND(cum_sell_alt_net::numeric, 1),
           open_trade_count, closed_trade_count
    FROM tbl_dna_model_summary_snapshots_5min s
    CROSS JOIN bounds b
    WHERE snapshot_timestamp >= b.day
      AND snapshot_timestamp < b.day + INTERVAL '1 day'
      AND model = ANY(%s)
    ORDER BY snapshot_timestamp;
"""

TOUCHED_RANK_ONE_SQL = """
    WITH bounds AS (SELECT %s::date AS day), ranked AS (
        SELECT model, snapshot_timestamp,
               DENSE_RANK() OVER (
                   PARTITION BY snapshot_timestamp
                   ORDER BY cum_net DESC
               ) AS position
        FROM tbl_dna_model_summary_snapshots_5min s
        CROSS JOIN bounds b
        WHERE snapshot_timestamp >= b.day
          AND snapshot_timestamp < b.day + INTERVAL '1 day'
          AND model = ANY(%s)
    )
    SELECT DISTINCT model
    FROM ranked
    WHERE position = 1;
"""


def _f(v) -> float:
    return float(v) if v is not None else 0.0


DSN: str | None = None  # set by dashboard_api.install() from settings.source_database_url; never DATABASE_URL (that is the intelligence repository DB here)


def _connect():
    if DSN:
        return psycopg2.connect(DSN, connect_timeout=5)
    return psycopg2.connect(
        host=os.environ.get("PGHOST", "localhost"),
        port=int(os.environ.get("PGPORT", "5432")),
        dbname=os.environ.get("PGDATABASE", "tradedb"),
        user=os.environ.get("PGUSER", "postgres"),
        password=os.environ.get("PGPASSWORD"),
        connect_timeout=5,
    )


STAT_COLS = ["model", "net", "alt", "trades", "wins", "losses", "win_rate",
             "alt_wins", "alt_win_rate", "product", "strategy", "target_profit", "product_type"]
MIN_SCENARIO_MODELS = 2  # fewer qualifying models -> scenario falls back to top_net


def _family_leaders(stats: list[dict], metric: str) -> list[dict]:
    """Return the best strategy in each canonical family for the chosen metric."""
    win_metric = "alt_win_rate" if metric == "alt" else "win_rate"
    winners: dict[str, dict] = {}
    for stat in stats:
        family = strategy_family(stat.get("strategy"))
        if family == "unknown":
            continue
        incumbent = winners.get(family)
        rank_key = (-stat[metric], -stat[win_metric], stat["model"])
        if incumbent is None or rank_key < (-incumbent[metric], -incumbent[win_metric], incumbent["model"]):
            winners[family] = stat
    family_order = ("breakout", "breakout_r", "breakout_rev", "breakout_r_rev")
    return [winners[family] for family in family_order if family in winners]


def _top_family(stats: list[dict], family: str, metric: str, limit: int = 5) -> list[dict]:
    """Return the strongest models in one family for the selected return metric."""
    win_metric = "alt_win_rate" if metric == "alt" else "win_rate"
    return sorted(
        (stat for stat in stats if strategy_family(stat.get("strategy")) == family),
        key=lambda stat: (-stat[metric], -stat[win_metric], stat["model"]),
    )[:limit]


TP_SL_RE = re.compile(r"(?:^|_)tp(?P<tp>\d+)_sl(?P<sl>\d+)(?:_|$)", re.IGNORECASE)
STRATEGY_SHAPE_RE = re.compile(
    r"^(?P<family>breakout(?:_r_rev|_rev|_r)?)_(?P<window>\d+)_tp(?P<tp>\d+)_sl(?P<sl>\d+)$",
    re.IGNORECASE,
)
CRYPTO_STRATEGY_SHAPE_RE = re.compile(
    r"^(?P<family>dna\d+_crypto)_tp(?P<tp>\d+)_sl(?P<sl>\d+)$",
    re.IGNORECASE,
)


def strategy_tp_sl(strategy: str | None) -> tuple[int, int] | None:
    """Extract the configured take-profit and stop-loss pair from a strategy name."""
    match = TP_SL_RE.search(strategy or "")
    return (int(match.group("tp")), int(match.group("sl"))) if match else None


def strategy_shape(strategy: str | None) -> dict | None:
    """Parse canonical Forex or Crypto family/window/TP/SL strategy names."""
    value = (strategy or "").strip()
    match = STRATEGY_SHAPE_RE.fullmatch(value)
    if match:
        return {
            "family": match.group("family").lower(),
            "window": int(match.group("window")),
            "tp": int(match.group("tp")),
            "sl": int(match.group("sl")),
        }
    match = CRYPTO_STRATEGY_SHAPE_RE.fullmatch(value)
    if not match:
        return None
    return {
        "family": match.group("family").lower(),
        "window": None,
        "tp": int(match.group("tp")),
        "sl": int(match.group("sl")),
    }


def _top_tp_sl(stats: list[dict], tp: int, sl: int, metric: str, limit: int = 3) -> list[dict]:
    """Return the strongest models for one exact TP/SL combination."""
    win_metric = "alt_win_rate" if metric == "alt" else "win_rate"
    return sorted(
        (stat for stat in stats if strategy_tp_sl(stat.get("strategy")) == (tp, sl)),
        key=lambda stat: (-stat[metric], -stat[win_metric], stat["model"]),
    )[:limit]


def _scenario_ids(stats: list[dict], snaps: dict[str, list[dict]], limit: int = 10,
                  touched_rank_one_ids: set[str] | None = None,
                  family_stats: list[dict] | None = None) -> dict[str, list[str]]:
    """Scenario model lists for one trading date.

    Rules reproduce the stored 14-18 Sep lists: each scenario filters the day's pool
    (Top 10 Net Return + Top 10 Win Rate) and falls back to Top 10 Net Return when fewer
    than MIN_SCENARIO_MODELS qualify. weakening_selection follows its catalogue text
    (high-volume pool models below their intraday peak) - the original rule is unknown.
    """
    by_net = sorted(stats, key=lambda s: (-s["net"], -s["win_rate"], s["model"]))
    top_net = by_net[:limit]
    top_alt = sorted(stats, key=lambda s: (-s["alt"], s["model"]))[:limit]
    top_win = sorted((s for s in stats if s["win_rate"] >= 50),
                     key=lambda s: (-s["win_rate"], -s["net"], s["model"]))[:limit]
    pool, seen = [], set()
    for s in top_net + top_win:
        if s["model"] not in seen:
            seen.add(s["model"])
            pool.append(s)

    def tp_pips(s):
        return (s["target_profit"] or 0) / 10

    def drawdown(s):
        series = snaps.get(s["model"]) or []
        return (max(p["net"] for p in series) - series[-1]["net"]) if series else 0.0

    def pick(models, pick_limit=None):
        models = list(models)[:pick_limit or limit]
        return models if len(models) >= MIN_SCENARIO_MODELS else top_net

    family_stats = family_stats if family_stats is not None else stats
    lists = {
        "top_net": top_net,
        "top_alt_net": top_alt,
        "family_leaders_net": _family_leaders(stats, "net"),
        "family_leaders_alt": _family_leaders(stats, "alt"),
        "top_win": top_win or top_net,
        "strongest_three": sorted(pool, key=lambda s: -s["net"])[:3],
        "strengthening_cluster": pick(s for s in pool if (s["strategy"] or "").startswith("breakout_R_")),
        "relative_value": pick(sorted((s for s in pool if s["win_rate"] >= 85), key=lambda s: -s["win_rate"])),
        "market_move": pick(s for s in pool if tp_pips(s) >= 10),
        "opposite_cluster": pick(s for s in pool if 3 <= tp_pips(s) <= 5),
        "weakening_selection": pick(sorted((s for s in pool if drawdown(s) > 0),
                                           key=lambda s: (-s["trades"], -drawdown(s)))),
        "repair_negative": pick(s for s in pool if s["win_rate"] == 100 and s["net"] > 0),
        # Every strategy that held the highest cumulative net at one or more
        # five-minute snapshots. Ties at #1 are deliberately included.
        "touched_rank_one": sorted(
            (s for s in stats if s["model"] in (touched_rank_one_ids or set())),
            key=lambda s: (-s["net"], -s["win_rate"], s["model"]),
        )[:limit],
    }
    for family in ("breakout", "breakout_r", "breakout_rev", "breakout_r_rev"):
        lists[f"top5_{family}_net"] = _top_family(family_stats, family, "net")
        lists[f"top5_{family}_alt"] = _top_family(family_stats, family, "alt")
    for tp, sl in sorted({pair for stat in stats if (pair := strategy_tp_sl(stat.get("strategy")))}):
        scenario_id = f"top3_tp{tp}_sl{sl}"
        lists[f"{scenario_id}_net"] = _top_tp_sl(stats, tp, sl, "net")
        lists[f"{scenario_id}_alt"] = _top_tp_sl(stats, tp, sl, "alt")
    lists["NET_RETURN"] = lists["top_net"]
    lists["WIN_RATE"] = lists["top_win"]
    return {k: [s["model"] for s in v] for k, v in lists.items()}


def build_point_in_time_scenario(date_str: str, at_time: str, scenario: str = "top_net",
                                 return_type: str = "NET", product_type: str = "all",
                                 product: str = "all", strategy_family_filter: str = "all",
                                 limit: int = 10, min_win_rate: float = 0.0) -> dict:
    """Re-evaluate a scenario from the full strategy universe at one snapshot time.

    Selection uses only the latest 5-minute snapshot and closed-trade evidence
    available on or before the requested time. Returned curves extend through
    the rest of the day so the captured cohort can be assessed afterwards.
    """
    product_type = normalize_product_type(product_type)
    product = normalize_product(product)
    strategy_family_filter = normalize_strategy_family(strategy_family_filter)
    limit = normalize_model_limit(limit)
    return_type = str(return_type or "NET").upper()
    if return_type not in {"NET", "ALT"}:
        raise ValueError("return_type must be NET or ALT")
    if not re.fullmatch(r"\d{2}:\d{2}", str(at_time)):
        raise ValueError("at_time must be HH:MM")
    hour, minute = map(int, at_time.split(":"))
    if hour > 23 or minute > 59:
        raise ValueError("at_time must be a valid HH:MM time")
    if not re.fullmatch(r"[A-Za-z0-9_.-]+", str(scenario)):
        raise ValueError("scenario contains unsupported characters")
    if not 0 <= float(min_win_rate) <= 100:
        raise ValueError("min_win_rate must be between 0 and 100")

    metric = "alt" if return_type == "ALT" else "net"
    scenario_key = scenario
    if scenario == "family_leaders" or scenario.startswith("top5_") or scenario.startswith("top3_tp"):
        scenario_key = f"{scenario}_{metric}"

    point_sql = """
        WITH bounds AS (
          SELECT %s::date AS day,
                 (%s::date + %s::time) AS cutoff
        ), model_meta AS (
          SELECT TRIM(model) AS model, MAX(LOWER(TRIM(product))) AS product,
                 MAX(TRIM(strategy_name)) AS strategy, MAX(target_profit) AS target_profit,
                 MAX(LOWER(TRIM(product_type))) AS product_type
          FROM product_forex
          WHERE product IS NOT NULL
            AND (%s = 'all' OR LOWER(TRIM(product_type)) = %s)
            AND (%s = 'all' OR LOWER(TRIM(product)) = %s)
          GROUP BY TRIM(model)
        ), asof_snap AS (
          SELECT DISTINCT ON (s.model) s.model, s.snapshot_timestamp,
                 s.cum_net, s.cum_alt_net, s.open_trade_count, s.closed_trade_count
          FROM tbl_dna_model_summary_snapshots_5min s CROSS JOIN bounds b
          WHERE s.snapshot_timestamp >= b.day AND s.snapshot_timestamp <= b.cutoff
          ORDER BY s.model, s.snapshot_timestamp DESC
        ), asof_trades AS (
          SELECT c.model, COUNT(*) AS trades,
                 COUNT(*) FILTER (WHERE c.net_return > 0) AS wins,
                 COUNT(*) FILTER (WHERE c.net_return <= 0) AS losses,
                 COUNT(*) FILTER (WHERE c.alt_net_return > 0) AS alt_wins
          FROM combined_trades_closed c CROSS JOIN bounds b
          WHERE c.created >= b.day AND c.created < b.day + INTERVAL '1 day'
            AND c.last_update <= b.cutoff
            AND (%s = 'all' OR LOWER(TRIM(c.product_type)) = %s)
            AND (%s = 'all' OR LOWER(TRIM(c.product)) = %s)
          GROUP BY c.model
        )
        SELECT m.model, m.product, m.strategy, m.target_profit, m.product_type,
               p.snapshot_timestamp, p.cum_net, p.cum_alt_net,
               p.open_trade_count, p.closed_trade_count,
               COALESCE(t.trades, 0), COALESCE(t.wins, 0), COALESCE(t.losses, 0),
               COALESCE(t.alt_wins, 0)
        FROM model_meta m JOIN asof_snap p ON p.model = m.model
        LEFT JOIN asof_trades t ON t.model = m.model
    """
    history_sql = """
        WITH bounds AS (SELECT %s::date AS day, (%s::date + %s::time) AS cutoff)
        SELECT s.model, to_char(s.snapshot_timestamp, 'HH24:MI'),
               ROUND(s.cum_net::numeric, 1), ROUND(s.cum_buy_net::numeric, 1),
               ROUND(s.cum_sell_net::numeric, 1), ROUND(s.cum_alt_net::numeric, 1),
               ROUND(s.cum_buy_alt_net::numeric, 1), ROUND(s.cum_sell_alt_net::numeric, 1),
               s.open_trade_count, s.closed_trade_count
        FROM tbl_dna_model_summary_snapshots_5min s CROSS JOIN bounds b
        WHERE s.snapshot_timestamp >= b.day AND s.snapshot_timestamp <= b.cutoff
          AND s.model = ANY(%s)
        ORDER BY s.model, s.snapshot_timestamp
    """
    with _connect() as conn, conn.cursor() as cur:
        cur.execute(point_sql, (date_str, date_str, at_time,
                                product_type, product_type, product, product,
                                product_type, product_type, product, product))
        rows = cur.fetchall()
        if not rows:
            return {"date": date_str, "at_time": at_time, "scenario": scenario_key, "models": []}

        stats = []
        for row in rows:
            model, prod, strategy, target_profit, ptype, snap_ts, net, alt, opened, snap_trades, trades, wins, losses, alt_wins = row
            trades = int(trades or snap_trades or 0)
            wins, losses, alt_wins = int(wins or 0), int(losses or 0), int(alt_wins or 0)
            stats.append({
                "model": model, "product": prod, "strategy": strategy or "",
                "target_profit": _f(target_profit), "product_type": ptype,
                "net": _f(net), "alt": _f(alt), "trades": trades,
                "wins": wins, "losses": losses,
                "win_rate": round(wins / trades * 100, 1) if trades else 0.0,
                "alt_wins": alt_wins,
                "alt_win_rate": round(alt_wins / trades * 100, 1) if trades else 0.0,
            })
        family_stats = list(stats)
        if strategy_family_filter != "all":
            stats = [s for s in stats if strategy_family(s["strategy"]) == strategy_family_filter]
        eligible_ids = {s["model"] for s in stats}
        cur.execute(history_sql, (date_str, date_str, at_time, sorted(eligible_ids)))
        snaps: dict[str, list[dict]] = {}
        for m, tm, net, buy, sell, alt_net, alt_buy, alt_sell, op, tr in cur.fetchall():
            if m not in eligible_ids:
                continue
            snaps.setdefault(m, []).append({"time": tm, "net": _f(net), "buy": _f(buy), "sell": _f(sell),
                "alt_net": _f(alt_net), "alt_buy": _f(alt_buy), "alt_sell": _f(alt_sell),
                "open": int(op or 0), "trades": int(tr or 0)})

        touched_rank_one_ids: set[str] = set()
        snapshots_by_time: dict[str, list[tuple[float, str]]] = {}
        for model, values in snaps.items():
            for point in values:
                snapshots_by_time.setdefault(point["time"], []).append((point["net"], model))
        for ranked in snapshots_by_time.values():
            if ranked:
                best = max(value for value, _ in ranked)
                touched_rank_one_ids.update(model for value, model in ranked if value == best)
        selected = _scenario_ids(stats, snaps, limit, touched_rank_one_ids, family_stats).get(scenario_key, [])
        stats_by_id = {s["model"]: s for s in family_stats}
        selected = [m for m in selected if stats_by_id[m]["win_rate"] >= float(min_win_rate)]
        if not selected:
            return {"date": date_str, "at_time": at_time, "scenario": scenario_key, "models": []}
        cur.execute(SNAP_SQL, (date_str, selected))
        full_series: dict[str, list[dict]] = {}
        for m, tm, net, buy, sell, alt_net, alt_buy, alt_sell, op, tr in cur.fetchall():
            full_series.setdefault(m, []).append({"time": tm, "net": _f(net), "buy": _f(buy), "sell": _f(sell),
                "alt_net": _f(alt_net), "alt_buy": _f(alt_buy), "alt_sell": _f(alt_sell),
                "open": int(op or 0), "trades": int(tr or 0)})

    models = []
    for rank, model in enumerate(selected, 1):
        stat = stats_by_id[model]
        series = full_series.get(model, [])
        head = series[-1] if series else {}
        models.append({
            "rank": rank, "model": model, "product": stat["product"],
            "product_type": stat["product_type"], "strategy": stat["strategy"],
            "color": COLORS[(rank - 1) % len(COLORS)], "trades": stat["trades"],
            "wins": stat["wins"], "losses": stat["losses"], "win_rate": stat["win_rate"],
            "alt_wins": stat["alt_wins"], "alt_win_rate": stat["alt_win_rate"],
            "cum_net": head.get("net", 0.0), "buy_net": head.get("buy", 0.0),
            "sell_net": head.get("sell", 0.0), "cum_alt_net": head.get("alt_net", 0.0),
            "buy_alt_net": head.get("alt_buy", 0.0), "sell_alt_net": head.get("alt_sell", 0.0),
            "series": series,
        })
    return {"date": date_str, "at_time": at_time, "scenario": scenario_key, "models": models}


def build_point_in_time_scenario_hours(date_str: str, scenario: str = "top_net",
                                       return_type: str = "NET", product_type: str = "all",
                                       product: str = "all", strategy_family_filter: str = "all",
                                       limit: int = 10, min_win_rate: float = 0.0) -> dict:
    """Return the selected strategy cohort at every completed clock-hour cutoff.

    The universe, snapshots, and closed-trade evidence are read once, then each
    hourly cohort is ranked using only data available by that cutoff.
    """
    product_type = normalize_product_type(product_type)
    product = normalize_product(product)
    strategy_family_filter = normalize_strategy_family(strategy_family_filter)
    limit = normalize_model_limit(limit)
    return_type = str(return_type or "NET").upper()
    if return_type not in {"NET", "ALT"}:
        raise ValueError("return_type must be NET or ALT")
    if not re.fullmatch(r"[A-Za-z0-9_.-]+", str(scenario)):
        raise ValueError("scenario contains unsupported characters")
    if not 0 <= float(min_win_rate) <= 100:
        raise ValueError("min_win_rate must be between 0 and 100")

    metric = "alt" if return_type == "ALT" else "net"
    scenario_key = scenario
    if scenario == "family_leaders" or scenario.startswith("top5_") or scenario.startswith("top3_tp"):
        scenario_key = f"{scenario}_{metric}"
    with _connect() as conn, conn.cursor() as cur:
        cur.execute("""
            SELECT TRIM(model), MAX(LOWER(TRIM(product))), MAX(TRIM(strategy_name)),
                   MAX(target_profit), MAX(LOWER(TRIM(product_type)))
            FROM product_forex
            WHERE product IS NOT NULL
              AND (%s = 'all' OR LOWER(TRIM(product_type)) = %s)
              AND (%s = 'all' OR LOWER(TRIM(product)) = %s)
            GROUP BY TRIM(model)
        """, (product_type, product_type, product, product))
        metadata = {row[0]: {"product": row[1], "strategy": row[2] or "",
                             "target_profit": _f(row[3]), "product_type": row[4]}
                    for row in cur.fetchall()}
        if not metadata:
            return {"date": date_str, "scenario": scenario_key, "hours": []}

        cur.execute("""
            SELECT model, snapshot_timestamp, cum_net, cum_buy_net, cum_sell_net,
                   cum_alt_net, cum_buy_alt_net, cum_sell_alt_net,
                   open_trade_count, closed_trade_count
            FROM tbl_dna_model_summary_snapshots_5min
            WHERE snapshot_timestamp >= %s::date
              AND snapshot_timestamp < %s::date + INTERVAL '1 day'
              AND model = ANY(%s)
            ORDER BY snapshot_timestamp, model
        """, (date_str, date_str, list(metadata)))
        snapshot_rows = cur.fetchall()
        cur.execute("""
            SELECT model, last_update, net_return, alt_net_return
            FROM combined_trades_closed
            WHERE created >= %s::date AND created < %s::date + INTERVAL '1 day'
              AND last_update >= %s::date AND last_update < %s::date + INTERVAL '1 day'
              AND (%s = 'all' OR LOWER(TRIM(product_type)) = %s)
              AND (%s = 'all' OR LOWER(TRIM(product)) = %s)
            ORDER BY last_update, model
        """, (date_str, date_str, date_str, date_str,
              product_type, product_type, product, product))
        trade_rows = cur.fetchall()

    def naive(value):
        return value.replace(tzinfo=None) if getattr(value, "tzinfo", None) else value

    snapshot_rows = [(model, naive(ts), _f(net), _f(buy), _f(sell), _f(alt),
                      _f(alt_buy), _f(alt_sell), int(opened or 0), int(closed or 0))
                     for model, ts, net, buy, sell, alt, alt_buy, alt_sell, opened, closed
                     in snapshot_rows if model in metadata]
    trade_rows = [(model, naive(ts), _f(net), _f(alt))
                  for model, ts, net, alt in trade_rows if model in metadata]
    if not snapshot_rows:
        return {"date": date_str, "scenario": scenario_key, "hours": []}

    day = dt.date.fromisoformat(date_str)
    first_snapshot_time = snapshot_rows[0][1]
    first_hour = first_snapshot_time.hour + int(bool(first_snapshot_time.minute or first_snapshot_time.second or first_snapshot_time.microsecond))
    last_hour = snapshot_rows[-1][1].hour
    snap_index = trade_index = 0
    latest: dict[str, tuple] = {}
    histories: dict[str, list[dict]] = {}
    closed: dict[str, list[tuple[float, float]]] = {}
    hourly = []
    for hour in range(first_hour, last_hour + 1):
        cutoff = dt.datetime.combine(day, dt.time(hour=hour))
        while snap_index < len(snapshot_rows) and snapshot_rows[snap_index][1] <= cutoff:
            row = snapshot_rows[snap_index]
            model, ts, net, buy, sell, alt, alt_buy, alt_sell, opened, trades = row
            latest[model] = row
            histories.setdefault(model, []).append({"time": ts.strftime("%H:%M"), "net": net,
                "buy": buy, "sell": sell, "alt_net": alt, "alt_buy": alt_buy,
                "alt_sell": alt_sell, "open": opened, "trades": trades})
            snap_index += 1
        while trade_index < len(trade_rows) and trade_rows[trade_index][1] <= cutoff:
            model, _, net, alt = trade_rows[trade_index]
            closed.setdefault(model, []).append((net, alt))
            trade_index += 1

        stats = []
        for model, row in latest.items():
            info = metadata[model]
            events = closed.get(model, [])
            trades = len(events) or row[9]
            wins = sum(1 for net, _ in events if net > 0)
            losses = sum(1 for net, _ in events if net <= 0)
            alt_wins = sum(1 for _, alt in events if alt > 0)
            win_rate = round(wins / trades * 100, 1) if trades else 0.0
            alt_win_rate = round(alt_wins / trades * 100, 1) if trades else 0.0
            stats.append({"model": model, **info, "net": row[2], "alt": row[5],
                "trades": trades, "wins": wins, "losses": losses, "win_rate": win_rate,
                "alt_wins": alt_wins, "alt_win_rate": alt_win_rate})
        family_stats = list(stats)
        if strategy_family_filter != "all":
            stats = [item for item in stats if strategy_family(item["strategy"]) == strategy_family_filter]
        eligible_ids = {item["model"] for item in stats}
        snaps = {model: points for model, points in histories.items() if model in eligible_ids}
        snapshots_by_time: dict[str, list[tuple[float, str]]] = {}
        for model, points in snaps.items():
            for point in points:
                snapshots_by_time.setdefault(point["time"], []).append((point["net"], model))
        touched_rank_one_ids: set[str] = set()
        for ranked in snapshots_by_time.values():
            if ranked:
                best = max(value for value, _ in ranked)
                touched_rank_one_ids.update(model for value, model in ranked if value == best)
        selected = _scenario_ids(stats, snaps, limit, touched_rank_one_ids, family_stats).get(scenario_key, [])
        stats_by_id = {item["model"]: item for item in family_stats}
        selected = [model for model in selected if stats_by_id[model]["win_rate"] >= float(min_win_rate)]
        cohort = [{"rank": rank, "model": model, "product": stats_by_id[model]["product"],
                   "strategy": stats_by_id[model]["strategy"], "trades": stats_by_id[model]["trades"],
                   "win_rate": stats_by_id[model]["win_rate"], "net": stats_by_id[model]["net"]}
                  for rank, model in enumerate(selected, 1)]
        hourly.append({"at_time": f"{hour:02d}:00", "models": cohort})
    return {"date": date_str, "scenario": scenario_key, "hours": hourly}


PRODUCT_TYPES = {"all", "forex", "crypto"}
STRATEGY_FAMILIES = {"all", "breakout", "breakout_r", "breakout_rev", "breakout_r_rev"}


def normalize_product_type(value: str | None) -> str:
    product_type = (value or "all").strip().lower()
    if product_type not in PRODUCT_TYPES:
        raise ValueError("product_type must be all, forex, or crypto")
    return product_type


def normalize_product(value: str | None) -> str:
    product = (value or "all").strip().lower()
    if product != "all" and not re.fullmatch(r"[a-z0-9._-]+", product):
        raise ValueError("product contains unsupported characters")
    return product


def strategy_family(value: str | None) -> str:
    name = (value or "").strip().lower()
    for family in ("breakout_r_rev", "breakout_rev", "breakout_r", "breakout"):
        if name == family or name.startswith(f"{family}_"):
            return family
    return "unknown"


def normalize_strategy_family(value: str | None) -> str:
    family = (value or "all").strip().lower()
    if family not in STRATEGY_FAMILIES:
        raise ValueError("strategy_family must be all, breakout, breakout_r, breakout_rev, or breakout_r_rev")
    return family


def normalize_model_limit(value: int | str | None) -> int:
    limit = int(value or 10)
    if limit not in (10, 20, 30):
        raise ValueError("limit must be 10, 20, or 30")
    return limit


_LIVE_DAY_CACHE: dict[tuple, tuple[float, dict]] = {}
LIVE_DAY_CACHE_SECONDS = 30


def build_live_day(date_str: str, product_type: str = "all", product: str = "all", strategy_family_filter: str = "all", limit: int = 10) -> dict:
    product_type = normalize_product_type(product_type)
    product = normalize_product(product)
    strategy_family_filter = normalize_strategy_family(strategy_family_filter)
    limit = normalize_model_limit(limit)
    cache_key = (date_str, product_type, product, strategy_family_filter, limit)
    cached = _LIVE_DAY_CACHE.get(cache_key)
    if cached and time.monotonic() - cached[0] < LIVE_DAY_CACHE_SECONDS:
        return cached[1]
    with _connect() as conn, conn.cursor() as cur:
        cur.execute(PRODUCTS_SQL, (product_type, product_type))
        products = [r[0] for r in cur.fetchall()]
        if product != "all" and product not in products:
            raise ValueError(f"product {product!r} is not available for type {product_type!r}")
        cur.execute(STATS_SQL, (date_str, product_type, product_type, product, product))
        stats = [dict(zip(STAT_COLS, r)) for r in cur.fetchall()]
        for s in stats:
            for k in ("net", "alt", "win_rate", "alt_win_rate", "target_profit"):
                s[k] = _f(s[k])
        product_stats = list(stats)
        if strategy_family_filter != "all":
            stats = [s for s in stats if strategy_family(s["strategy"]) == strategy_family_filter]

        # Snapshots for every model that can appear in a scenario (top net / alt / win-rate pools)
        candidates = {s["model"] for s in sorted(stats, key=lambda s: -s["net"])[:limit]}
        candidates |= {s["model"] for s in sorted(stats, key=lambda s: -s["alt"])[:limit]}
        candidates |= {s["model"] for s in sorted((s for s in stats if s["win_rate"] >= 50),
                                                  key=lambda s: (-s["win_rate"], -s["net"], s["model"]))[:limit]}
        candidates |= {s["model"] for s in _family_leaders(stats, "net")}
        candidates |= {s["model"] for s in _family_leaders(stats, "alt")}
        for family in ("breakout", "breakout_r", "breakout_rev", "breakout_r_rev"):
            candidates |= {s["model"] for s in _top_family(product_stats, family, "net")}
            candidates |= {s["model"] for s in _top_family(product_stats, family, "alt")}
        tp_sl_pairs = sorted({pair for stat in stats if (pair := strategy_tp_sl(stat.get("strategy")))})
        for tp, sl in tp_sl_pairs:
            candidates |= {s["model"] for s in _top_tp_sl(stats, tp, sl, "net")}
            candidates |= {s["model"] for s in _top_tp_sl(stats, tp, sl, "alt")}
        touched_rank_one_ids: set[str] = set()
        all_model_ids = [s["model"] for s in stats]
        if all_model_ids:
            cur.execute(TOUCHED_RANK_ONE_SQL, (date_str, all_model_ids))
            touched_rank_one_ids = {row[0] for row in cur.fetchall()}
            candidates |= touched_rank_one_ids
        snaps: dict[str, list[dict]] = {}
        if candidates:
            cur.execute(SNAP_SQL, (date_str, sorted(candidates)))
            for m, tm, net, buy, sell, a_net, a_buy, a_sell, op, tr in cur.fetchall():
                snaps.setdefault(m, []).append({
                    "time": tm, "net": _f(net), "buy": _f(buy), "sell": _f(sell),
                    "alt_net": _f(a_net), "alt_buy": _f(a_buy), "alt_sell": _f(a_sell),
                    "open": int(op or 0), "trades": int(tr or 0),
                })

    by_model = {s["model"]: s for s in product_stats}

    def model_list(ids: list[str]) -> list[dict]:
        out = []
        for rank, m in enumerate(ids, start=1):
            s = by_model[m]
            series = snaps.get(m) or [{
                "time": "02:00", "net": s["net"], "buy": 0.0, "sell": s["net"],
                "alt_net": s["alt"], "alt_buy": 0.0, "alt_sell": s["alt"],
                "open": 0, "trades": int(s["trades"]),
            }]
            last = series[-1]
            out.append({
                "rank": rank, "model": m, "product": s["product"] or "GBP",
                "product_type": s["product_type"] or "forex",
                "strategy": s["strategy"] or "breakout_strategy",
                "color": COLORS[(rank - 1) % len(COLORS)],
                "trades": int(s["trades"]), "wins": int(s["wins"]), "losses": int(s["losses"]),
                "win_rate": s["win_rate"], "alt_wins": int(s["alt_wins"]), "alt_win_rate": s["alt_win_rate"],
                "cum_net": last["net"], "buy_net": last["buy"], "sell_net": last["sell"],
                "cum_alt_net": last["alt_net"], "buy_alt_net": last["alt_buy"],
                "sell_alt_net": last["alt_sell"], "series": series,
            })
        return out

    payload = {"date": date_str, "product_type": product_type, "product": product,
               "strategy_family": strategy_family_filter, "limit": limit,
               "products": products,
               "tp_sl_scenarios": [
                   {"id": f"top3_tp{tp}_sl{sl}", "tp": tp, "sl": sl}
                   for tp, sl in tp_sl_pairs
               ],
               "generated_at": dt.datetime.now().isoformat(timespec="seconds")}
    for sc, ids in _scenario_ids(stats, snaps, limit, touched_rank_one_ids, product_stats).items():
        payload[sc] = model_list(ids)
    _LIVE_DAY_CACHE[cache_key] = (time.monotonic(), payload)
    if len(_LIVE_DAY_CACHE) > 64:
        cutoff = time.monotonic() - LIVE_DAY_CACHE_SECONDS
        for key, value in list(_LIVE_DAY_CACHE.items()):
            if value[0] < cutoff:
                _LIVE_DAY_CACHE.pop(key, None)
    return payload


def build_portfolio_day(date_str: str, model_ids: list[str]) -> dict:
    clean_ids = list(dict.fromkeys(str(m).strip() for m in model_ids if str(m).strip()))
    if not clean_ids or len(clean_ids) > 10:
        raise ValueError("portfolio requires between 1 and 10 unique models")
    if any(not re.fullmatch(r"[A-Za-z0-9._-]+", model) for model in clean_ids):
        raise ValueError("portfolio contains an invalid model id")

    with _connect() as conn, conn.cursor() as cur:
        cur.execute(STATS_SQL, (date_str, "all", "all", "all", "all"))
        stats = [dict(zip(STAT_COLS, row)) for row in cur.fetchall()]
        stats = [s for s in stats if s["model"] in clean_ids]
        for stat in stats:
            for key in ("net", "alt", "win_rate", "alt_win_rate", "target_profit"):
                stat[key] = _f(stat[key])
        cur.execute(SNAP_SQL, (date_str, clean_ids))
        snaps: dict[str, list[dict]] = {}
        for model, tm, net, buy, sell, a_net, a_buy, a_sell, op, trades in cur.fetchall():
            snaps.setdefault(model, []).append({
                "time": tm, "net": _f(net), "buy": _f(buy), "sell": _f(sell),
                "alt_net": _f(a_net), "alt_buy": _f(a_buy), "alt_sell": _f(a_sell),
                "open": int(op or 0), "trades": int(trades or 0),
            })

    by_model = {s["model"]: s for s in stats}
    models = []
    for rank, model in enumerate(clean_ids, start=1):
        stat = by_model.get(model)
        if not stat:
            continue
        series = snaps.get(model) or [{
            "time": "02:00", "net": stat["net"], "buy": 0.0, "sell": stat["net"],
            "alt_net": stat["alt"], "alt_buy": 0.0, "alt_sell": stat["alt"],
            "open": 0, "trades": int(stat["trades"]),
        }]
        last = series[-1]
        models.append({
            "rank": rank, "model": model, "product": stat["product"] or "GBP",
            "product_type": stat["product_type"] or "forex",
            "strategy": stat["strategy"] or "breakout_strategy",
            "color": COLORS[(rank - 1) % len(COLORS)],
            "trades": int(stat["trades"]), "wins": int(stat["wins"]), "losses": int(stat["losses"]),
            "win_rate": stat["win_rate"], "alt_wins": int(stat["alt_wins"]), "alt_win_rate": stat["alt_win_rate"],
            "cum_net": last["net"], "buy_net": last["buy"], "sell_net": last["sell"],
            "cum_alt_net": last["alt_net"], "buy_alt_net": last["alt_buy"],
            "sell_alt_net": last["alt_sell"], "series": series,
        })
    return {"date": date_str, "requested_models": clean_ids, "models": models,
            "generated_at": dt.datetime.now().isoformat(timespec="seconds")}


def build_similar_strategies(date_str: str, model_id: str) -> dict:
    """Return same-product comparison sets that vary one strategy dimension only."""
    model_id = str(model_id or "").strip()
    if not re.fullmatch(r"[A-Za-z0-9._-]+", model_id):
        raise ValueError("model contains unsupported characters")
    with _connect() as conn, conn.cursor() as cur:
        cur.execute(STATS_SQL, (date_str, "all", "all", "all", "all"))
        stats = [dict(zip(STAT_COLS, row)) for row in cur.fetchall()]
    reference = next((stat for stat in stats if stat["model"] == model_id), None)
    if not reference:
        raise ValueError(f"model {model_id!r} has no trades on {date_str}")
    reference_shape = strategy_shape(reference.get("strategy"))
    if not reference_shape:
        raise ValueError(f"strategy {reference.get('strategy')!r} is not a supported family/window/TP/SL strategy")

    same_product = [
        stat for stat in stats
        if (stat.get("product") or "").strip().lower() == (reference.get("product") or "").strip().lower()
        and (stat.get("product_type") or "").strip().lower() == (reference.get("product_type") or "").strip().lower()
        and strategy_shape(stat.get("strategy"))
    ]
    dimensions = ("family", "window", "tp", "sl")
    family_order = {name: index for index, name in enumerate(("breakout", "breakout_r", "breakout_rev", "breakout_r_rev"))}
    groups: dict[str, list[dict]] = {}
    for dimension in dimensions:
        fixed_dimensions = [name for name in dimensions if name != dimension]
        matches = [
            stat for stat in same_product
            if all(strategy_shape(stat["strategy"])[name] == reference_shape[name] for name in fixed_dimensions)
        ]
        matches.sort(key=lambda stat: (
            family_order.get(strategy_shape(stat["strategy"])[dimension], 99)
            if dimension == "family" else (strategy_shape(stat["strategy"])[dimension] if strategy_shape(stat["strategy"])[dimension] is not None else -1),
            stat["model"],
        ))
        groups[dimension] = [
            {
                "model": stat["model"],
                "product": stat["product"],
                "product_type": stat["product_type"],
                "strategy": stat["strategy"],
                "value": strategy_shape(stat["strategy"])[dimension],
            }
            for stat in matches[:10]
        ]
    return {
        "date": date_str,
        "reference": {
            "model": reference["model"], "product": reference["product"],
            "product_type": reference["product_type"], "strategy": reference["strategy"],
            **reference_shape,
        },
        "groups": groups,
        "generated_at": dt.datetime.now().isoformat(timespec="seconds"),
    }


def build_strategy_catalog(date_str: str) -> dict:
    """Return active models and parsed strategy dimensions for portfolio selection."""
    with _connect() as conn, conn.cursor() as cur:
        cur.execute(STATS_SQL, (date_str, "all", "all", "all", "all"))
        stats = [dict(zip(STAT_COLS, row)) for row in cur.fetchall()]
    models = []
    for stat in stats:
        shape = strategy_shape(stat.get("strategy"))
        if not shape:
            continue
        models.append({
            "model": stat["model"],
            "product": (stat.get("product") or "").strip().lower(),
            "product_type": (stat.get("product_type") or "").strip().lower(),
            "strategy": stat["strategy"],
            "net": _f(stat.get("net")),
            "alt": _f(stat.get("alt")),
            **shape,
        })
    family_order = {name: index for index, name in enumerate(("breakout", "breakout_r", "breakout_rev", "breakout_r_rev"))}
    models.sort(key=lambda item: (
        item["product_type"], item["product"], family_order.get(item["family"], 99),
        item["window"] if item["window"] is not None else -1, item["tp"], item["sl"], item["model"],
    ))
    return {"date": date_str, "models": models, "generated_at": dt.datetime.now().isoformat(timespec="seconds")}


TRADES_CLOSED_SQL = """
    SELECT 'closed', to_char(created, 'YYYY-MM-DD HH24:MI:SS'), to_char(last_update, 'YYYY-MM-DD HH24:MI:SS'),
           TRIM(signal), TRIM(product), entry_price, latest_price, trade_quantity,
           net_return, alt_net_return, min_net_return, max_net_return,
           TRIM(close_type), TRIM(trade_reason), TRIM(strategy_name), target_profit, target_loss
    FROM combined_trades_closed
    WHERE model = %s AND created::date BETWEEN %s AND %s
    ORDER BY created;
"""

TRADES_OPEN_SQL = """
    SELECT 'open', to_char(created, 'YYYY-MM-DD HH24:MI:SS'), to_char(last_update, 'YYYY-MM-DD HH24:MI:SS'),
           TRIM(signal), TRIM(product), entry_price, latest_price, trade_quantity,
           net_return, alt_net_return, min_net_return, max_net_return,
           NULL, TRIM(trade_reason), TRIM(strategy_name), target_profit, target_loss
    FROM combined_trades_open
    WHERE TRIM(model) = %s AND created::date BETWEEN %s AND %s
    ORDER BY created;
"""

TRADE_COLS = [
    "status", "opened", "last_update", "signal", "product", "entry_price", "latest_price",
    "quantity", "net_return", "alt_net_return", "min_net_return", "max_net_return",
    "close_type", "trade_reason", "strategy", "target_profit", "target_loss",
]


def build_model_trades(model: str, date_from: str, date_to: str, product_type: str = "all", product: str = "all") -> dict:
    product_type = normalize_product_type(product_type)
    product = normalize_product(product)
    with _connect() as conn, conn.cursor() as cur:
        rows = []
        for sql in (TRADES_OPEN_SQL, TRADES_CLOSED_SQL):
            cur.execute(sql.replace("ORDER BY created;", "AND (%s = 'all' OR LOWER(TRIM(product_type)) = %s) AND (%s = 'all' OR LOWER(TRIM(product)) = %s) ORDER BY created;"),
                        (model, date_from, date_to, product_type, product_type, product, product))
            rows += cur.fetchall()
        # Canonical model definition: {script}_{window}_tp{tp}_sl{sl} plus params, e.g. breakout_2_tp5_sl20
        cur.execute(
            "SELECT TRIM(strategy_name), TRIM(strategy_params) FROM product_forex WHERE TRIM(model) = %s AND (%s = 'all' OR LOWER(TRIM(product_type)) = %s) AND (%s = 'all' OR LOWER(TRIM(product)) = %s) LIMIT 1",
            (model, product_type, product_type, product, product),
        )
        pf = cur.fetchone() or (None, None)
    trades = []
    for r in rows:
        t = dict(zip(TRADE_COLS, r))
        for k in ("entry_price", "latest_price", "quantity", "net_return",
                  "alt_net_return", "min_net_return", "max_net_return",
                  "target_profit", "target_loss"):
            t[k] = float(t[k]) if t[k] is not None else None
        trades.append(t)
    return {
        "model": model, "from": date_from, "to": date_to, "product_type": product_type, "product": product,
        "strategy_name": pf[0], "strategy_params": pf[1], "trades": trades,
    }


def build_hourly_family_report(date_str: str, product_type: str = "all",
                               product: str = "all", family: str = "all",
                               interval_minutes: int = 60) -> dict:
    """Return uncached time-bucketed entries, exits, and point-in-time open exposure."""
    product_type = normalize_product_type(product_type)
    product = normalize_product(product)
    family = normalize_strategy_family(family)
    if interval_minutes not in (10, 30, 60, 180):
        raise ValueError("interval_minutes must be 10, 30, 60, or 180")
    day = dt.date.fromisoformat(date_str)
    family_pattern = {
        "all": r"^(breakout(_r_rev|_rev|_r)?_[0-9]+|dna3_crypto)_tp[0-9]+_sl[0-9]+$",
        "breakout": r"^breakout_[0-9]+_tp[0-9]+_sl[0-9]+$",
        "breakout_r": r"^breakout_r_[0-9]+_tp[0-9]+_sl[0-9]+$",
        "breakout_rev": r"^breakout_rev_[0-9]+_tp[0-9]+_sl[0-9]+$",
        "breakout_r_rev": r"^breakout_r_rev_[0-9]+_tp[0-9]+_sl[0-9]+$",
    }[family]
    scope_sql = """
      AND (%s = 'all' OR LOWER(BTRIM(t.product_type)) = %s)
      AND (%s = 'all' OR LOWER(BTRIM(t.product)) = %s)
      AND LOWER(
            CASE
              WHEN BTRIM(t.strategy_name) ~* '^dna3_crypto_tp[0-9]+_sl[0-9]+$'
                THEN regexp_replace(BTRIM(t.strategy_name), '^dna3_crypto_', 'breakout_3_', 'i')
              ELSE COALESCE(BTRIM(t.strategy_name), '')
            END
          ) ~ %s
    """
    with _connect() as conn, conn.cursor() as cur:
        cur.execute(
            """SELECT DISTINCT LOWER(BTRIM(product))
                 FROM product_forex
                WHERE product IS NOT NULL
                  AND (%s = 'all' OR LOWER(BTRIM(product_type)) = %s)
                ORDER BY 1""",
            (product_type, product_type),
        )
        products = [row[0] for row in cur.fetchall()]
        params = (product_type, product_type, product, product, family_pattern)
        cur.execute(
            """SELECT t.created, t.last_update, UPPER(BTRIM(t.signal)),
                      t.net_return, t.alt_net_return
                 FROM combined_trades_closed t
                WHERE t.created < %s::date + INTERVAL '1 day'
                  AND t.last_update >= %s::date
            """ + scope_sql,
            (date_str, date_str, *params),
        )
        trades = [
            {"opened": opened, "closed": closed, "side": side,
             "net": _f(net), "alt": _f(alt)}
            for opened, closed, side, net, alt in cur.fetchall()
        ]
        cur.execute(
            """SELECT t.created, NULL, UPPER(BTRIM(t.signal)),
                      t.net_return, t.alt_net_return
                 FROM combined_trades_open t
                WHERE t.created < %s::date + INTERVAL '1 day'
            """ + scope_sql,
            (date_str, *params),
        )
        trades.extend(
            {"opened": opened, "closed": None, "side": side,
             "net": _f(net), "alt": _f(alt)}
            for opened, _, side, net, alt in cur.fetchall()
        )

    now = dt.datetime.now()
    is_today = day == now.date()
    day_start = dt.datetime.combine(day, dt.time.min)
    current_bucket = (
        day_start + dt.timedelta(
            minutes=((now.hour * 60 + now.minute) // interval_minutes) * interval_minutes
        )
        if is_today else None
    )
    rows = []
    totals = {"opened_trades": 0, "closed_trades": 0, "net_profit_count": 0, "alt_profit_count": 0,
              "total_net": 0.0, "total_alt_net": 0.0}
    bucket_count = (
        int((current_bucket - day_start).total_seconds() // (interval_minutes * 60)) + 1
        if current_bucket else 1440 // interval_minutes
    )
    for bucket_number in range(bucket_count):
        hour_start = day_start + dt.timedelta(minutes=bucket_number * interval_minutes)
        hour_end = hour_start + dt.timedelta(minutes=interval_minutes)
        checkpoint = now if current_bucket and hour_start == current_bucket else hour_end
        for side in ("BUY", "SELL"):
            side_trades = [trade for trade in trades if trade["side"] == side]
            opened = sum(hour_start <= trade["opened"] < checkpoint for trade in side_trades)
            closed = [trade for trade in side_trades if trade["closed"] and hour_start <= trade["closed"] < checkpoint]
            open_at_end = sum(
                trade["opened"] < checkpoint and (trade["closed"] is None or trade["closed"] >= checkpoint)
                for trade in side_trades
            )
            if not (opened or closed or open_at_end or (current_bucket and hour_start == current_bucket)):
                continue
            total_net = sum(trade["net"] for trade in closed)
            total_alt = sum(trade["alt"] for trade in closed)
            row = {
                "exit_hour": hour_start.strftime("%H:%M"), "side": side,
                "opened_trades": opened, "open_at_hour_end": open_at_end,
                "closed_trades": len(closed),
                "net_profit_count": sum(trade["net"] > 0 for trade in closed),
                "alt_profit_count": sum(trade["alt"] > 0 for trade in closed),
                "avg_net": total_net / len(closed) if closed else 0.0,
                "avg_alt_net": total_alt / len(closed) if closed else 0.0,
                "total_net": total_net, "total_alt_net": total_alt,
                "is_incomplete_hour": bool(current_bucket and hour_start == current_bucket),
            }
            rows.append(row)
            totals["opened_trades"] += opened
            for key in ("closed_trades", "net_profit_count", "alt_profit_count"):
                totals[key] += row[key]
            totals["total_net"] += total_net
            totals["total_alt_net"] += total_alt
    live_open = {side: sum(trade["side"] == side and trade["closed"] is None for trade in trades)
                 for side in ("BUY", "SELL")}
    totals.update({"open_buy": live_open["BUY"], "open_sell": live_open["SELL"]})
    return {
        "date": date_str, "product_type": product_type, "product": product,
        "family": family, "products": products, "rows": rows, "summary": totals,
        "is_today": is_today,
        "current_hour": current_bucket.strftime("%H:%M") if current_bucket else None,
        "interval_minutes": interval_minutes,
        "generated_at": now.isoformat(timespec="seconds"),
    }


DATE_RE = re.compile(r"\d{4}-\d{2}-\d{2}")
