"""Re-vendor app/dashboard_queries.py from ep_057 top10_live_server.py, or check it for drift.

Version history:
- 1.0.0 (2026-09-26): Added after the vendored copy went stale within hours (ep_057 changed the hourly report's crypto
  strategy-name handling at 17:20 the same day). Usage:
    python -m sync.vendor_dashboard_queries          # rewrite app/dashboard_queries.py
    python -m sync.vendor_dashboard_queries --check  # exit 1 if the vendored copy differs from a fresh vendoring
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT.parents[1] / "ep_057_sql_to_pgsql" / "dashboards_and_uis" / "top10_live_server.py"
DST = ROOT / "app" / "dashboard_queries.py"

HEADER = '''# epics/ep_058_strategy_intelligence_pg/hosted_directory/app/dashboard_queries.py — vendored query builders.
#
# GENERATED by sync/vendor_dashboard_queries.py from ep_057 dashboards_and_uis/top10_live_server.py ({version}).
# Do not edit by hand; re-run the script (or --check for drift).
"""Query builders behind the Top10 5-min equity curve dashboard (live_day, portfolio_day, similar_strategies,
strategy_catalog, model_trades, hourly_family_report). Reads PostgreSQL tradedb via DSN (set by dashboard_api.install)."""
'''


def build() -> str:
    text = SRC.read_text(encoding="utf-8")
    version = re.search(r"^# (v[\d.]+) ", text, re.M).group(1)
    body = text[: text.index("class Handler")].rstrip() + "\n"
    body = body[body.index("from __future__"):]
    for line in ("from functools import partial\n", "from http.server import SimpleHTTPRequestHandler, ThreadingHTTPServer\n",
                 "from pathlib import Path\n", "from urllib.parse import parse_qs, urlparse\n"):
        body = body.replace(line, "")
    body = re.sub(r"HERE = Path.*?\n", "", body)
    body = re.sub(r"PORT = int.*?\n", "", body)
    body = re.sub(r"try:\n    from dotenv import load_dotenv\n\n    load_dotenv\(HERE.*?\)\nexcept ImportError:\n    pass\n", "", body, flags=re.S)
    old = 'def _connect():\n    if os.environ.get("DATABASE_URL"):\n        return psycopg2.connect(os.environ["DATABASE_URL"], connect_timeout=5)'
    new = ('DSN: str | None = None  # set by dashboard_api.install() from settings.source_database_url; never DATABASE_URL '
           '(that is the intelligence repository DB here)\n\n\ndef _connect():\n    if DSN:\n        return psycopg2.connect(DSN, connect_timeout=5)')
    if old not in body:
        raise SystemExit("ep_057 _connect() changed shape; update this script")
    return HEADER.format(version=version) + body.replace(old, new)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    fresh = build()
    if parser.parse_args().check:
        same = DST.read_text(encoding="utf-8") == fresh
        print("in sync" if same else "DRIFT: app/dashboard_queries.py differs from ep_057 top10_live_server.py")
        return 0 if same else 1
    DST.write_text(fresh, encoding="utf-8")
    print(f"wrote {DST}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
